$(document).ready(function () {
        $('#vehicle-make').change(function () {
            var selectedMake = $(this).val();
            $('#vehicle-model').empty(); // Clear previous options

            // Populate vehicle models based on the selected make
            switch (selectedMake) {
                case 'Alfa Romeo':
                    $('#vehicle-model').append('<option value="Alfa Romeo Giulietta">Alfa Romeo Giulietta</option>');
                    $('#vehicle-model').append('<option value="Alfa Romeo 159">Alfa Romeo 159</option>');
                    break;
                case 'Audi':
                    $('#vehicle-model').append('<option value="Audi A3 Sedan">Audi A3 Sedan</option>');
                    $('#vehicle-model').append('<option value="Audi RS4 Avant">Audi RS4 Avant</option>');
                    $('#vehicle-model').append('<option value="Audi A5 Sportback">Audi A5 Sportback</option>');
                    $('#vehicle-model').append('<option value="Audi RS5 Sportback">Audi RS5 Sportback</option>');
                    $('#vehicle-model').append('<option value="Audi RS6 Avant">Audi RS6 Avant</option>');
                    $('#vehicle-model').append('<option value="Audi A7 Sportback">Audi A7 Sportback</option>');
                    $('#vehicle-model').append('<option value="Audi RS7 Sportback">Audi RS7 Sportback</option>');
                    $('#vehicle-model').append('<option value="Audi A8">Audi A8</option>');
                    $('#vehicle-model').append('<option value="Audi Q2">Audi Q2</option>');
                    $('#vehicle-model').append('<option value="Audi Q3">Audi Q3</option>');
                    $('#vehicle-model').append('<option value="Audi Q3 Sportback">Audi Q3 Sportback</option>');
                    $('#vehicle-model').append('<option value="Audi Q5">Audi Q5</option>');
                    $('#vehicle-model').append('<option value="Audi Q5 Sportback">Audi Q5 Sportback</option>');
                    $('#vehicle-model').append('<option value="Audi Q8">Audi Q8</option>');
                    $('#vehicle-model').append('<option value="Audi Q8 e-tron">Audi Q8 e-tron</option>');
                    $('#vehicle-model').append('<option value="Audi e-tron GT">Audi e-tron GT</option>');
                    $('#vehicle-model').append('<option value="Audi Q8 e-tron Sportback">Audi Q8 e-tron Sportback</option>');
                    $('#vehicle-model').append('<option value="Audi SQ8 e-tron">Audi SQ8 e-tron</option>');
                    $('#vehicle-model').append('<option value="Audi SQ8 Sportback e-tron">Audi SQ8 Sportback e-tron</option>');
                    $('#vehicle-model').append('<option value="Audi RSQ8">Audi RSQ8</option>');
                    break;
                case 'BMW':
                    $('#vehicle-model').append('<option value="BMW M135i">BMW M135i</option>');
                    $('#vehicle-model').append('<option value="BMW M2 Coupe">BMW M2 Coupe</option>');
                    $('#vehicle-model').append('<option value="BMW 2 Series Gran Coupe">BMW 2 Series Gran Coupe</option>');
                    $('#vehicle-model').append('<option value="BMW 3 Series">BMW 3 Series</option>');
                    $('#vehicle-model').append('<option value="BMW 3 Series M">BMW 3 Series M</option>');
                    $('#vehicle-model').append('<option value="BMW M3">BMW M3</option>');
                    $('#vehicle-model').append('<option value="BMW 4 Series Coupe">BMW 4 Series Coupe</option>');
                    $('#vehicle-model').append('<option value="BMW M4 Coupe">BMW M4 Coupe</option>');
                    $('#vehicle-model').append('<option value="BMW i4">BMW i4</option>');
                    $('#vehicle-model').append('<option value="BMW i4 M50">BMW i4 M50</option>');
                    $('#vehicle-model').append('<option value="BMW 5 Series">BMW 5 Series</option>');
                    $('#vehicle-model').append('<option value="BMW i5">BMW i5</option>');
                    $('#vehicle-model').append('<option value="BMW M5">BMW M5</option>');
                    $('#vehicle-model').append('<option value="BMW 6 Series GT">BMW 6 Series GT</option>');
                    $('#vehicle-model').append('<option value="BMW 7 Series">BMW 7 Series</option>');
                    $('#vehicle-model').append('<option value="BMW i7">BMW i7</option>');
                    $('#vehicle-model').append('<option value="BMW 8 Series M Coupe">BMW 8 Series M Coupe</option>');
                    $('#vehicle-model').append('<option value="BMW 8 Series Gran Coupe">BMW 8 Series Gran Coupe</option>');
                    $('#vehicle-model').append('<option value="BMW X1">BMW X1</option>');
                    $('#vehicle-model').append('<option value="BMW iX1">BMW iX1</option>');
                    $('#vehicle-model').append('<option value="BMW iX3">BMW iX3</option>');
                    $('#vehicle-model').append('<option value="BMW X3">BMW X3</option>');
                    $('#vehicle-model').append('<option value="BMW X4">BMW X4</option>');
                    $('#vehicle-model').append('<option value="BMW iX">BMW iX</option>');
                    $('#vehicle-model').append('<option value="BMW X5">BMW X5</option>');
                    $('#vehicle-model').append('<option value="BMW X6">BMW X6</option>');
                    $('#vehicle-model').append('<option value="BMW X7">BMW X7</option>');
                    $('#vehicle-model').append('<option value="BMW Z4">BMW Z4</option>');
                    $('#vehicle-model').append('<option value="BMW iX M60">BMW iX M60</option>');
                    break;
                case 'Borgward':
                    $('#vehicle-model').append('<option value="Borgward BX5">Borgward BX5</option>');
                    break;
                case 'Chery':
                    $('#vehicle-model').append('<option value="Chery Omoda 5">Chery Omoda 5</option>');
                    $('#vehicle-model').append('<option value="Chery Tiggo 8 Pro">Chery Tiggo 8 Pro</option>');
                    $('#vehicle-model').append('<option value="Chery Omoda E5">Chery Omoda E5</option>');
                    break;
                case 'Chevrolet':
                    $('#vehicle-model').append('<option value="Chevrolet Sonic">Chevrolet Sonic</option>');
                    $('#vehicle-model').append('<option value="Chevrolet Sonic Sedan">Chevrolet Sonic Sedan</option>');
                    $('#vehicle-model').append('<option value="Chevrolet Malibu">Chevrolet Malibu</option>');
                    $('#vehicle-model').append('<option value="Chevrolet Cruze">Chevrolet Cruze</option>');
                    $('#vehicle-model').append('<option value="Chevrolet Orlando">Chevrolet Orlando</option>');
                    $('#vehicle-model').append('<option value="Chevrolet Captiva">Chevrolet Captiva</option>');
                    $('#vehicle-model').append('<option value="Chevrolet Colorado">Chevrolet Colorado</option>');
                    break;
                case 'Citroen':
                    $('#vehicle-model').append('<option value="Citroen DS3">Citroen DS3</option>');
                    $('#vehicle-model').append('<option value="Citroen DS4">Citroen DS4</option>');
                    $('#vehicle-model').append('<option value="Citroen DS5">Citroen DS5</option>');
                    $('#vehicle-model').append('<option value="Citroen DS7 Crossback">Citroen DS7 Crossback</option>');
                    $('#vehicle-model').append('<option value="Citroen C4 Picasso">Citroen C4 Picasso</option>');
                    $('#vehicle-model').append('<option value="Citroen Grand C4 Picasso">Citroen Grand C4 Picasso</option>');
                    break;
                case 'Ford':
                    $('#vehicle-model').append('<option value="Ford Ranger">Ford Ranger</option>');
                    $('#vehicle-model').append('<option value="Ford Ranger Raptor">Ford Ranger Raptor</option>');
                    $('#vehicle-model').append('<option value="Ford Mustang">Ford Mustang</option>');
                    $('#vehicle-model').append('<option value="Ford Everest">Ford Everest</option>');
                    $('#vehicle-model').append('<option value="Ford Fiesta">Ford Fiesta</option>');
                    $('#vehicle-model').append('<option value="Ford Fiesta Sedan">Ford Fiesta Sedan</option>');
                    $('#vehicle-model').append('<option value="Ford Fiesta ST">Ford Fiesta ST</option>');
                    $('#vehicle-model').append('<option value="Ford Focus">Ford Focus</option>');
                    $('#vehicle-model').append('<option value="Ford Focus Sedan">Ford Focus Sedan</option>');
                    $('#vehicle-model').append('<option value="Ford Focus ST">Ford Focus ST</option>');
                    $('#vehicle-model').append('<option value="Ford Mondeo">Ford Mondeo</option>');
                    $('#vehicle-model').append('<option value="Ford S-MAX">Ford S-MAX</option>');
                    $('#vehicle-model').append('<option value="Ford EcoSport">Ford EcoSport</option>');
                    $('#vehicle-model').append('<option value="Ford Kuga">Ford Kuga</option>');
                    break;
                case 'Honda':
                    $('#vehicle-model').append('<option value="Honda WR-V">Honda WR-V</option>');
                    $('#vehicle-model').append('<option value="Honda City">Honda City</option>');
                    $('#vehicle-model').append('<option value="Honda City Hatchback">Honda City Hatchback</option>');
                    $('#vehicle-model').append('<option value="Honda Civic">Honda Civic</option>');
                    $('#vehicle-model').append('<option value="Honda Civic Type R">Honda Civic Type R</option>');
                    $('#vehicle-model').append('<option value="Honda Accord">Honda Accord</option>');
                    $('#vehicle-model').append('<option value="Honda HR-V">Honda HR-V</option>');
                    $('#vehicle-model').append('<option value="Honda CR-V">Honda CR-V</option>');
                    $('#vehicle-model').append('<option value="Honda Jazz">Honda Jazz</option>');
                    $('#vehicle-model').append('<option value="Honda BR-V">Honda BR-V</option>');
                    $('#vehicle-model').append('<option value="Honda Stream">Honda Stream</option>');
                    $('#vehicle-model').append('<option value="Honda Odyssey">Honda Odyssey</option>');
                    $('#vehicle-model').append('<option value="Honda CR-Z">Honda CR-Z</option>');
                    break;
                case 'Hyundai':
                    $('#vehicle-model').append('<option value="Hyundai Creta">Hyundai Creta</option>');
                    $('#vehicle-model').append('<option value="Hyundai Kona">Hyundai Kona</option>');
                    $('#vehicle-model').append('<option value="Hyundai Kona Electric">Hyundai Kona Electric</option>');
                    $('#vehicle-model').append('<option value="Hyundai Tucson">Hyundai Tucson</option>');
                    $('#vehicle-model').append('<option value="Hyundai Ioniq 5">Hyundai Ioniq 5</option>');
                    $('#vehicle-model').append('<option value="Hyundai Ioniq 6">Hyundai Ioniq 6</option>');
                    $('#vehicle-model').append('<option value="Hyundai Palisade">Hyundai Palisade</option>');
                    $('#vehicle-model').append('<option value="Hyundai Staria">Hyundai Staria</option>');
                    $('#vehicle-model').append('<option value="Hyundai i10">Hyundai i10</option>');
                    $('#vehicle-model').append('<option value="Hyundai Elantra">Hyundai Elantra</option>');
                    $('#vehicle-model').append('<option value="Hyundai Ioniq">Hyundai Ioniq</option>');
                    $('#vehicle-model').append('<option value="Hyundai i30">Hyundai i30</option>');
                    $('#vehicle-model').append('<option value="Hyundai i30 N">Hyundai i30 N</option>');
                    $('#vehicle-model').append('<option value="Hyundai Veloster">Hyundai Veloster</option>');
                    $('#vehicle-model').append('<option value="Hyundai Sonata">Hyundai Sonata</option>');
                    $('#vehicle-model').append('<option value="Hyundai i40 Sedan">Hyundai i40 Sedan</option>');
                    $('#vehicle-model').append('<option value="Hyundai i40 Tourer">Hyundai i40 Tourer</option>');
                    $('#vehicle-model').append('<option value="Hyundai Santa Fe">Hyundai Santa Fe</option>');
                    $('#vehicle-model').append('<option value="Hyundai Grand Starex">Hyundai Grand Starex</option>');
                    $('#vehicle-model').append('<option value="Hyundai Genesis">Hyundai Genesis</option>');
                    break;
                case 'Infiniti':
                    $('#vehicle-model').append('<option value="Infiniti Q50">Infiniti Q50</option>');
                    $('#vehicle-model').append('<option value="Infiniti Q60">Infiniti Q60</option>');
                    $('#vehicle-model').append('<option value="Infiniti Q70">Infiniti Q70</option>');
                    $('#vehicle-model').append('<option value="Infiniti QX50">Infiniti QX50</option>');
                    $('#vehicle-model').append('<option value="Infiniti QX70">Infiniti QX70</option>');
                    $('#vehicle-model').append('<option value="Infiniti QX80">Infiniti QX80</option>');
                    break;
                case 'Isuzu':
                    $('#vehicle-model').append('<option value="Isuzu D-MAX">Isuzu D-MAX</option>');
                    $('#vehicle-model').append('<option value="Isuzu MU-X">Isuzu MU-X</option>');
                    break;
                case 'Jaguar':
                    $('#vehicle-model').append('<option value="Jaguar XE">Jaguar XE</option>');
                    $('#vehicle-model').append('<option value="Jaguar XF">Jaguar XF</option>');
                    $('#vehicle-model').append('<option value="Jaguar XJ">Jaguar XJ</option>');
                    $('#vehicle-model').append('<option value="Jaguar F-Pace">Jaguar F-Pace</option>');
                    $('#vehicle-model').append('<option value="Jaguar I-Pace">Jaguar I-Pace</option>');
                    break;
                case 'Jeep':
                    $('#vehicle-model').append('<option value="Jeep Compass">Jeep Compass</option>');
                    $('#vehicle-model').append('<option value="Jeep Cherokee">Jeep Cherokee</option>');
                    $('#vehicle-model').append('<option value="Jeep Grand Cherokee">Jeep Grand Cherokee</option>');
                    $('#vehicle-model').append('<option value="Jeep Grand Cherokee SRT">Jeep Grand Cherokee SRT</option>');
                    $('#vehicle-model').append('<option value="Jeep Wrangler">Jeep Wrangler</option>');
                    break;
                case 'Kia':
                    $('#vehicle-model').append('<option value="Kia Niro EV">Kia Niro EV</option>');
                    $('#vehicle-model').append('<option value="Kia Sorento">Kia Sorento</option>');
                    $('#vehicle-model').append('<option value="Kia Carnival">Kia Carnival</option>');
                    $('#vehicle-model').append('<option value="Kia EV6">Kia EV6</option>');
                    $('#vehicle-model').append('<option value="Kia Picanto">Kia Picanto</option>');
                    $('#vehicle-model').append('<option value="Kia Rio">Kia Rio</option>');
                    $('#vehicle-model').append('<option value="Kia Rio Sedan">Kia Rio Sedan</option>');
                    $('#vehicle-model').append('<option value="Kia Cerato">Kia Cerato</option>');
                    $('#vehicle-model').append('<option value="Kia Cerato Koup">Kia Cerato Koup</option>');
                    $('#vehicle-model').append('<option value="Kia Optima">Kia Optima</option>');
                    $('#vehicle-model').append('<option value="Kia Stinger">Kia Stinger</option>');
                    $('#vehicle-model').append('<option value="Kia Sportage">Kia Sportage</option>');
                    $('#vehicle-model').append('<option value="Kia Pregio">Kia Pregio</option>');
                    $('#vehicle-model').append('<option value="Kia Seltos">Kia Seltos</option>');
                    break;
                case 'Land Rover':
                    $('#vehicle-model').append('<option value="Land Rover Defender">Land Rover Defender</option>');
                    $('#vehicle-model').append('<option value="Land Rover Discovery Sport">Land Rover Discovery Sport</option>');
                    $('#vehicle-model').append('<option value="Land Rover Discovery">Land Rover Discovery</option>');
                    $('#vehicle-model').append('<option value="Land Rover Range Rover Evoque">Land Rover Range Rover Evoque</option>');
                    $('#vehicle-model').append('<option value="Land Rover Range Rover Velar">Land Rover Range Rover Velar</option>');
                    $('#vehicle-model').append('<option value="Land Rover Range Rover Sport">Land Rover Range Rover Sport</option>');
                    $('#vehicle-model').append('<option value="Land Rover Range Rover">Land Rover Range Rover</option>');
                    break;
                case 'Lexus':
                    $('#vehicle-model').append('<option value="Lexus ES">Lexus ES</option>');
                    $('#vehicle-model').append('<option value="Lexus LS">Lexus LS</option>');
                    $('#vehicle-model').append('<option value="Lexus NX">Lexus NX</option>');
                    $('#vehicle-model').append('<option value="Lexus RX">Lexus RX</option>');
                    $('#vehicle-model').append('<option value="Lexus LX">Lexus LX</option>');
                    $('#vehicle-model').append('<option value="Lexus LC">Lexus LC</option>');
                    $('#vehicle-model').append('<option value="Lexus UX">Lexus UX</option>');
                    $('#vehicle-model').append('<option value="Lexus LM">Lexus LM</option>');
                    $('#vehicle-model').append('<option value="Lexus CT">Lexus CT</option>');
                    $('#vehicle-model').append('<option value="Lexus IS">Lexus IS</option>');
                    $('#vehicle-model').append('<option value="Lexus RC">Lexus RC</option>');
                    $('#vehicle-model').append('<option value="Lexus RC F">Lexus RC F</option>');
                    $('#vehicle-model').append('<option value="Lexus GS">Lexus GS</option>');
                    $('#vehicle-model').append('<option value="Lexus GS F">Lexus GS F</option>');
                    break;
                case 'Mazda':
                    $('#vehicle-model').append('<option value="Mazda 2 Hatchback">Mazda 2 Hatchback</option>');
                    $('#vehicle-model').append('<option value="Mazda 2 Sedan">Mazda 2 Sedan</option>');
                    $('#vehicle-model').append('<option value="Mazda 3 Hatchback">Mazda 3 Hatchback</option>');
                    $('#vehicle-model').append('<option value="Mazda 3 Sedan">Mazda 3 Sedan</option>');
                    $('#vehicle-model').append('<option value="Mazda 6 Sedan">Mazda 6 Sedan</option>');
                    $('#vehicle-model').append('<option value="Mazda 6 Grand Touring">Mazda 6 Grand Touring</option>');
                    $('#vehicle-model').append('<option value="Mazda CX-3">Mazda CX-3</option>');
                    $('#vehicle-model').append('<option value="Mazda CX-5">Mazda CX-5</option>');
                    $('#vehicle-model').append('<option value="Mazda CX-8">Mazda CX-8</option>');
                    $('#vehicle-model').append('<option value="Mazda CX-9">Mazda CX-9</option>');
                    $('#vehicle-model').append('<option value="Mazda BT-50">Mazda BT-50</option>');
                    $('#vehicle-model').append('<option value="Mazda MX-5">Mazda MX-5</option>');
                    $('#vehicle-model').append('<option value="Mazda CX-30">Mazda CX-30</option>');
                    $('#vehicle-model').append('<option value="Mazda MX-30">Mazda MX-30</option>');
                    $('#vehicle-model').append('<option value="Mazda 8">Mazda 8</option>');
                    break;
                case 'Mercedes-Benz':
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG A-Class">Mercedes-Benz AMG A-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz A-Class Sedan">Mercedes-Benz A-Class Sedan</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG A-Class Sedan">Mercedes-Benz AMG A-Class Sedan</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz B-Class">Mercedes-Benz B-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz CLA">Mercedes-Benz CLA</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG CLA">Mercedes-Benz AMG CLA</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz GLA">Mercedes-Benz GLA</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLA">Mercedes-Benz AMG GLA</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz EQA">Mercedes-Benz EQA</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz GLB">Mercedes-Benz GLB</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLB">Mercedes-Benz AMG GLB</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz EQB">Mercedes-Benz EQB</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz C-Class">Mercedes-Benz C-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG C-Class">Mercedes-Benz AMG C-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz C-Class Coupe">Mercedes-Benz C-Class Coupe</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG C-Class Coupe">Mercedes-Benz AMG C-Class Coupe</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz GLC">Mercedes-Benz GLC</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLC">Mercedes-Benz AMG GLC</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz GLC Coupe">Mercedes-Benz GLC Coupe</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLC Coupe">Mercedes-Benz AMG GLC Coupe</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz EQC">Mercedes-Benz EQC</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz E-Class">Mercedes-Benz E-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG E-Class">Mercedes-Benz AMG E-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz E-Class Coupe">Mercedes-Benz E-Class Coupe</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz CLS">Mercedes-Benz CLS</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG CLS">Mercedes-Benz AMG CLS</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz GLE Coupe">Mercedes-Benz GLE Coupe</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz GLE">Mercedes-Benz GLE</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLE Coupe">Mercedes-Benz AMG GLE Coupe</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz S-Class">Mercedes-Benz S-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz Maybach S-Class">Mercedes-Benz Maybach S-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz EQS">Mercedes-Benz EQS</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG S-Class Coupe">Mercedes-Benz AMG S-Class Coupe</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz S-Class Cabriolet">Mercedes-Benz S-Class Cabriolet</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz GLS">Mercedes-Benz GLS</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz Maybach GLS">Mercedes-Benz Maybach GLS</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG G-Class">Mercedes-Benz AMG G-Class</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz Vito Tourer">Mercedes-Benz Vito Tourer</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz SLC">Mercedes-Benz SLC</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG GT">Mercedes-Benz AMG GT</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG GT 4-Door">Mercedes-Benz AMG GT 4-Door</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz EQE">Mercedes-Benz EQE</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG EQS">Mercedes-Benz AMG EQS</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG EQE">Mercedes-Benz AMG EQE</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz AMG SL">Mercedes-Benz AMG SL</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz EQS SUV">Mercedes-Benz EQS SUV</option>');
                    $('#vehicle-model').append('<option value="Mercedes-Benz EQE SUV">Mercedes-Benz EQE SUV</option>');
                    break;
                case 'MINI':
                    $('#vehicle-model').append('<option value="MINI 3 Door">MINI 3 Door</option>');
                    $('#vehicle-model').append('<option value="MINI 5 Door">MINI 5 Door</option>');
                    $('#vehicle-model').append('<option value="MINI Clubman">MINI Clubman</option>');
                    $('#vehicle-model').append('<option value="MINI Countryman">MINI Countryman</option>');
                    $('#vehicle-model').append('<option value="MINI Electric">MINI Electric</option>');
                    $('#vehicle-model').append('<option value="MINI Convertible">MINI Convertible</option>');
                    $('#vehicle-model').append('<option value="MINI Coupe">MINI Coupe</option>');
                    break;
                case 'Mitsubishi':
                    $('#vehicle-model').append('<option value="Mitsubishi Triton">Mitsubishi Triton</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi Xpander">Mitsubishi Xpander</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi Mirage">Mitsubishi Mirage</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi Attrage">Mitsubishi Attrage</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi Lancer">Mitsubishi Lancer</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi Lancer Sportback">Mitsubishi Lancer Sportback</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi ASX">Mitsubishi ASX</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi Outlander">Mitsubishi Outlander</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi Pajero">Mitsubishi Pajero</option>');
                    $('#vehicle-model').append('<option value="Mitsubishi Pajero Sport">Mitsubishi Pajero Sport</option>');
                    break;
                case 'Nissan':
                    $('#vehicle-model').append('<option value="Nissan Almera">Nissan Almera</option>');
                    $('#vehicle-model').append('<option value="Nissan Leaf">Nissan Leaf</option>');
                    $('#vehicle-model').append('<option value="Nissan Serena S-Hybrid">Nissan Serena S-Hybrid</option>');
                    $('#vehicle-model').append('<option value="Nissan X-Trail">Nissan X-Trail</option>');
                    $('#vehicle-model').append('<option value="Nissan Navara">Nissan Navara</option>');
                    $('#vehicle-model').append('<option value="Nissan NV200">Nissan NV200</option>');
                    $('#vehicle-model').append('<option value="Nissan Latio Sedan">Nissan Latio Sedan</option>');
                    $('#vehicle-model').append('<option value="Nissan Latio Hatchback">Nissan Latio Hatchback</option>');
                    $('#vehicle-model').append('<option value="Nissan Sylphy">Nissan Sylphy</option>');
                    $('#vehicle-model').append('<option value="Nissan Teana">Nissan Teana</option>');
                    $('#vehicle-model').append('<option value="Nissan X-Gear">Nissan X-Gear</option>');
                    $('#vehicle-model').append('<option value="Nissan Grand Livina">Nissan Grand Livina</option>');
                    $('#vehicle-model').append('<option value="Nissan Murano">Nissan Murano</option>');
                    $('#vehicle-model').append('<option value="Nissan Elgrand">Nissan Elgrand</option>');
                    $('#vehicle-model').append('<option value="Nissan 370Z Coupe">Nissan 370Z Coupe</option>');
                    $('#vehicle-model').append('<option value="Nissan 370Z Roadster">Nissan 370Z Roadster</option>');
                    $('#vehicle-model').append('<option value="Nissan NV350 Urvan">Nissan NV350 Urvan</option>');
                    break;
                case 'Perodua':
                    $('#vehicle-model').append('<option value="Perodua Axia">Perodua Axia</option>');
                    $('#vehicle-model').append('<option value="Perodua Bezza">Perodua Bezza</option>');
                    $('#vehicle-model').append('<option value="Perodua Myvi">Perodua Myvi</option>');
                    $('#vehicle-model').append('<option value="Perodua Alza">Perodua Alza</option>');
                    $('#vehicle-model').append('<option value="Perodua Aruz">Perodua Aruz</option>');
                    $('#vehicle-model').append('<option value="Perodua Ativa">Perodua Ativa</option>');
                    $('#vehicle-model').append('<option value="Perodua Viva">Perodua Viva</option>');
                    $('#vehicle-model').append('<option value="Perodua Kenari">Perodua Kenari</option>');
                    break;
                case 'Peugeot':
                    $('#vehicle-model').append('<option value="Peugeot 2008">Peugeot 2008</option>');
                    $('#vehicle-model').append('<option value="Peugeot 3008">Peugeot 3008</option>');
                    $('#vehicle-model').append('<option value="Peugeot 5008">Peugeot 5008</option>');
                    $('#vehicle-model').append('<option value="Peugeot Landtrek">Peugeot Landtrek</option>');
                    $('#vehicle-model').append('<option value="Peugeot 208">Peugeot 208</option>');
                    $('#vehicle-model').append('<option value="Peugeot 208 GTi">Peugeot 208 GTi</option>');
                    $('#vehicle-model').append('<option value="Peugeot 308">Peugeot 308</option>');
                    $('#vehicle-model').append('<option value="Peugeot 408">Peugeot 408</option>');
                    $('#vehicle-model').append('<option value="Peugeot 508">Peugeot 508</option>');
                    $('#vehicle-model').append('<option value="Peugeot 508 SW">Peugeot 508 SW</option>');
                    $('#vehicle-model').append('<option value="Peugeot RCZ">Peugeot RCZ</option>');
                    break;
                case 'Proton':
                    $('#vehicle-model').append('<option value="Proton Saga">Proton Saga</option>');
                    $('#vehicle-model').append('<option value="Proton Iriz">Proton Iriz</option>');
                    $('#vehicle-model').append('<option value="Proton Persona">Proton Persona</option>');
                    $('#vehicle-model').append('<option value="Proton S70">Proton S70</option>');
                    $('#vehicle-model').append('<option value="Proton Exora">Proton Exora</option>');
                    $('#vehicle-model').append('<option value="Proton X50">Proton X50</option>');
                    $('#vehicle-model').append('<option value="Proton X70">Proton X70</option>');
                    $('#vehicle-model').append('<option value="Proton X90">Proton X90</option>');
                    $('#vehicle-model').append('<option value="Proton Satria Neo">Proton Satria Neo</option>');
                    $('#vehicle-model').append('<option value="Proton Preve">Proton Preve</option>');
                    $('#vehicle-model').append('<option value="Proton Suprima S">Proton Suprima S</option>');
                    $('#vehicle-model').append('<option value="Proton Inspira">Proton Inspira</option>');
                    $('#vehicle-model').append('<option value="Proton Perdana">Proton Perdana</option>');
                    $('#vehicle-model').append('<option value="Proton Ertiga">Proton Ertiga</option>');
                    break;
                case 'Subaru':
                    $('#vehicle-model').append('<option value="Subaru WRX">Subaru WRX</option>');
                    $('#vehicle-model').append('<option value="Subaru Outback">Subaru Outback</option>');
                    $('#vehicle-model').append('<option value="Subaru XV">Subaru XV</option>');
                    $('#vehicle-model').append('<option value="Subaru Forester">Subaru Forester</option>');
                    $('#vehicle-model').append('<option value="Subaru BRZ">Subaru BRZ</option>');
                    $('#vehicle-model').append('<option value="Subaru Legacy Sedan">Subaru Legacy Sedan</option>');
                    $('#vehicle-model').append('<option value="Subaru Legacy Wagon">Subaru Legacy Wagon</option>');
                    break;
                case 'Suzuki':
                    $('#vehicle-model').append('<option value="Suzuki Swift Sport">Suzuki Swift Sport</option>');
                    $('#vehicle-model').append('<option value="Suzuki Jimny">Suzuki Jimny</option>');
                    $('#vehicle-model').append('<option value="Suzuki Alto">Suzuki Alto</option>');
                    $('#vehicle-model').append('<option value="Suzuki Swift">Suzuki Swift</option>');
                    $('#vehicle-model').append('<option value="Suzuki SX4">Suzuki SX4</option>');
                    $('#vehicle-model').append('<option value="Suzuki S-Cross">Suzuki S-Cross</option>');
                    $('#vehicle-model').append('<option value="Suzuki Kizashi">Suzuki Kizashi</option>');
                    $('#vehicle-model').append('<option value="Suzuki Grand Vitara">Suzuki Grand Vitara</option>');
                    break;
                case 'Toyota':
                    $('#vehicle-model').append('<option value="Toyota Yaris">Toyota Yaris</option>');
                    $('#vehicle-model').append('<option value="Toyota Vios">Toyota Vios</option>');
                    $('#vehicle-model').append('<option value="Toyota Corolla">Toyota Corolla</option>');
                    $('#vehicle-model').append('<option value="Toyota Camry">Toyota Camry</option>');
                    $('#vehicle-model').append('<option value="Toyota Veloz">Toyota Veloz</option>');
                    $('#vehicle-model').append('<option value="Toyota Innova">Toyota Innova</option>');
                    $('#vehicle-model').append('<option value="Toyota Innova Zenix">Toyota Innova Zenix</option>');
                    $('#vehicle-model').append('<option value="Toyota Alphard">Toyota Alphard</option>');
                    $('#vehicle-model').append('<option value="Toyota Vellfire">Toyota Vellfire</option>');
                    $('#vehicle-model').append('<option value="Toyota Corolla Cross">Toyota Corolla Cross</option>');
                    $('#vehicle-model').append('<option value="Toyota Fortuner">Toyota Fortuner</option>');
                    $('#vehicle-model').append('<option value="Toyota Harrier">Toyota Harrier</option>');
                    $('#vehicle-model').append('<option value="Toyota Hilux">Toyota Hilux</option>');
                    $('#vehicle-model').append('<option value="Toyota GR Supra">Toyota GR Supra</option>');
                    $('#vehicle-model').append('<option value="Toyota Hiace">Toyota Hiace</option>');
                    $('#vehicle-model').append('<option value="Toyota GR86">Toyota GR86</option>');
                    $('#vehicle-model').append('<option value="Toyota GR Corolla">Toyota GR Corolla</option>');
                    $('#vehicle-model').append('<option value="Toyota GR Yaris">Toyota GR Yaris</option>');
                    $('#vehicle-model').append('<option value="Toyota Avanza">Toyota Avanza</option>');
                    $('#vehicle-model').append('<option value="Toyota Sienta">Toyota Sienta</option>');
                    $('#vehicle-model').append('<option value="Toyota Previa">Toyota Previa</option>');
                    $('#vehicle-model').append('<option value="Toyota Rush">Toyota Rush</option>');
                    $('#vehicle-model').append('<option value="Toyota C-HR">Toyota C-HR</option>');
                    $('#vehicle-model').append('<option value="Toyota RAV4">Toyota RAV4</option>');
                    $('#vehicle-model').append('<option value="Toyota 86">Toyota 86</option>');
                    $('#vehicle-model').append('<option value="Toyota Prius">Toyota Prius</option>');
                    $('#vehicle-model').append('<option value="Toyota Prius c">Toyota Prius c</option>');
                    break;
                case 'Volkswagen':
                    $('#vehicle-model').append('<option value="Volkswagen Golf GTI">Volkswagen Golf GTI</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Golf R">Volkswagen Golf R</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Arteon">Volkswagen Arteon</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Tiguan Allspace">Volkswagen Tiguan Allspace</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Touareg">Volkswagen Touareg</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Vento">Volkswagen Vento</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Polo">Volkswagen Polo</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Polo GTI">Volkswagen Polo GTI</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Jetta">Volkswagen Jetta</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Golf">Volkswagen Golf</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Beetle">Volkswagen Beetle</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Scirocco">Volkswagen Scirocco</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Scirocco R">Volkswagen Scirocco R</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Eos">Volkswagen Eos</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Passat">Volkswagen Passat</option>');
                    $('#vehicle-model').append('<option value="Volkswagen CC">Volkswagen CC</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Passat CC R-Line">Volkswagen Passat CC R-Line</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Tiguan">Volkswagen Tiguan</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Cross Touran">Volkswagen Cross Touran</option>');
                    $('#vehicle-model').append('<option value="Volkswagen Sharan">Volkswagen Sharan</option>');
                    break;
                case 'Volvo':
                    $('#vehicle-model').append('<option value="Volvo XC40">Volvo XC40</option>');
                    $('#vehicle-model').append('<option value="Volvo XC40 Recharge Electric">Volvo XC40 Recharge Electric</option>');
                    $('#vehicle-model').append('<option value="Volvo S60">Volvo S60</option>');
                    $('#vehicle-model').append('<option value="Volvo V60">Volvo V60</option>');
                    $('#vehicle-model').append('<option value="Volvo XC60">Volvo XC60</option>');
                    $('#vehicle-model').append('<option value="Volvo S90">Volvo S90</option>');
                    $('#vehicle-model').append('<option value="Volvo XC90">Volvo XC90</option>');
                    $('#vehicle-model').append('<option value="Volvo C40">Volvo C40</option>');
                    $('#vehicle-model').append('<option value="Volvo V40">Volvo V40</option>');
                    $('#vehicle-model').append('<option value="Volvo S80">Volvo S80</option>');
                    $('#vehicle-model').append('<option value="Volvo V90">Volvo V90</option>');
                    break;
            }
        });
    });