$(document).ready(function () {
    $('#vehicle-make').change(function () {
        var selectedMake = $(this).val();
        $('#vehicle-model').empty(); // Clear previous options

        // Populate vehicle models based on the selected make
        switch (selectedMake) {
            case 'Perodua':
                $('#vehicle-model').append('<option value="Perodua Kembara">Perodua Kembara</option>');
                $('#vehicle-model').append('<option value="Perodua Myvi">Perodua Myvi</option>');
                $('#vehicle-model').append('<option value="Perodua Myvi Lagi Best">Perodua Myvi Lagi Best</option>');
                $('#vehicle-model').append('<option value="Perodua Myvi (2018+)">Perodua Myvi (2018+)</option>');
                $('#vehicle-model').append('<option value="Perodua Myvi Advanced (2018-2021)">Perodua Myvi Advanced (2018-2021)</option>');
                $('#vehicle-model').append('<option value="Perodua Myvi Advanced (2022+)">Perodua Myvi Advanced (2022+)</option>');
                $('#vehicle-model').append('<option value="Perodua Kancil">Perodua Kancil</option>');
                $('#vehicle-model').append('<option value="Perodua Kelisa">Perodua Kelisa</option>');
                $('#vehicle-model').append('<option value="Perodua Kenari">Perodua Kenari</option>');
                $('#vehicle-model').append('<option value="Perodua Rusa">Perodua Rusa</option>');
                $('#vehicle-model').append('<option value="Perodua Alza (2009-2021)">Perodua Alza (2009-2021)</option>');
                $('#vehicle-model').append('<option value="Perodua Alza (2022+)">Perodua Alza (2022+)</option>');
                $('#vehicle-model').append('<option value="Perodua Nautica">Perodua Nautica</option>');
                $('#vehicle-model').append('<option value="Perodua Bezza">Perodua Bezza</option>');
                $('#vehicle-model').append('<option value="Perodua Bezza (Camera) (2020+)">Perodua Bezza (Camera) (2020+)</option>');
                $('#vehicle-model').append('<option value="Perodua Axia">Perodua Axia</option>');
                $('#vehicle-model').append('<option value="Perodua Axia (Camera) (2021+)">Perodua Axia (Camera) (2021+)</option>');
                $('#vehicle-model').append('<option value="Perodua Viva">Perodua Viva</option>');
                $('#vehicle-model').append('<option value="Perodua Aruz (Camera)">Perodua Aruz (Camera)</option>');
                $('#vehicle-model').append('<option value="Perodua Aruz (no Camera)">Perodua Aruz (no Camera)</option>');
                $('#vehicle-model').append('<option value="Perodua Ativa (Camera)">Perodua Ativa (Camera)</option>');
                $('#vehicle-model').append('<option value="Perodua Ativa">Perodua Ativa</option>');
                break;
            case 'Proton':
                $('#vehicle-model').append('<option value="Proton Saga / Iswara">Proton Saga / Iswara</option>');
                $('#vehicle-model').append('<option value="Proton Saga BLM / FLX">Proton Saga BLM / FLX</option>');
                $('#vehicle-model').append('<option value="Proton Wira">Proton Wira</option>');
                $('#vehicle-model').append('<option value="Proton Satria">Proton Satria</option>');
                $('#vehicle-model').append('<option value="Proton Satria Neo">Proton Satria Neo</option>');
                $('#vehicle-model').append('<option value="Proton Exora">Proton Exora</option>');
                $('#vehicle-model').append('<option value="Proton Waja">Proton Waja</option>');
                $('#vehicle-model').append('<option value="Proton Juara">Proton Juara</option>');
                $('#vehicle-model').append('<option value="Proton Preve">Proton Preve</option>');
                $('#vehicle-model').append('<option value="Proton Suprema S">Proton Suprema S</option>');
                $('#vehicle-model').append('<option value="Proton Inspira">Proton Inspira</option>');
                $('#vehicle-model').append('<option value="Proton Perdana">Proton Perdana</option>');
                $('#vehicle-model').append('<option value="Proton Ertiga">Proton Ertiga</option>');
                $('#vehicle-model').append('<option value="Proton Saga vvt (2016+)">Proton Saga vvt (2016+)</option>');
                $('#vehicle-model').append('<option value="Proton Iriz">Proton Iriz</option>');
                $('#vehicle-model').append('<option value="Proton Gen2">Proton Gen2</option>');
                $('#vehicle-model').append('<option value="Proton Persona (2011-2017)">Proton Persona (2011-2017)</option>');
                $('#vehicle-model').append('<option value="Proton Persona (2018+)">Proton Persona (2018+)</option>');
                $('#vehicle-model').append('<option value="Proton X70 Standard">Proton X70 Standard</option>');
                $('#vehicle-model').append('<option value="Proton X70 Executive">Proton X70 Executive</option>');
                $('#vehicle-model').append('<option value="Proton X70 Premium (Camera)">Proton X70 Premium (Camera)</option>');
                $('#vehicle-model').append('<option value="Proton X90 Lane Assist">Proton X90 Lane Assist</option>');
                $('#vehicle-model').append('<option value="Proton X50 Standard">Proton X50 Standard</option>');
                $('#vehicle-model').append('<option value="Proton X50 Executive, Premium, TGDI(Camera)">Proton X50 Executive, Premium, TGDI(Camera)</option>');
                $('#vehicle-model').append('<option value="Proton S70 Executive / Premium (2024+)">Proton S70 Executive / Premium (2024+)</option>');
                $('#vehicle-model').append('<option value="Proton S70 Flagship / Flagship X (2024+)">Proton S70 Flagship / Flagship X (2024+)</option>');
                break;
            case 'Honda (Car)':
                $('#vehicle-model').append('<option value="Honda Elysion (2004-2014)">Honda Elysion (2004-2014)</option>');
                $('#vehicle-model').append('<option value="Honda Elysion (2015+)">Honda Elysion (2015+)</option>');
                $('#vehicle-model').append('<option value="Honda Freed">Honda Freed</option>');
                $('#vehicle-model').append('<option value="Honda CRV S10">Honda CRV S10</option>');
                $('#vehicle-model').append('<option value="Honda CRV S9A">Honda CRV S9A</option>');
                $('#vehicle-model').append('<option value="Honda CRV WQ (2007-2012)">Honda CRV WQ (2007-2012)</option>');
                $('#vehicle-model').append('<option value="Honda CRV (2009-2016)">Honda CRV (2009-2016)</option>');
                $('#vehicle-model').append('<option value="Honda CRV (2017+)">Honda CRV (2017+)</option>');
                $('#vehicle-model').append('<option value="Honda CRV (Sensing) (2017+)">Honda CRV (Sensing) (2017+)</option>');
                $('#vehicle-model').append('<option value="Honda Insight">Honda Insight</option>');
                $('#vehicle-model').append('<option value="Honda City MN (2003-2008)">Honda City MN (2003-2008)</option>');
                $('#vehicle-model').append('<option value="Honda City 2px (2009-2013)">Honda City 2px (2009-2013)</option>');
                $('#vehicle-model').append('<option value="Honda City (2014-2020)">Honda City (2014-2020)</option>');
                $('#vehicle-model').append('<option value="Honda City (2021+)">Honda City (2021+)</option>');
                $('#vehicle-model').append('<option value="Honda Accord S84 (1999-2004)">Honda Accord S84 (1999-2004)</option>');
                $('#vehicle-model').append('<option value="Honda Accord UA (2004-2007)">Honda Accord UA (2004-2007)</option>');
                $('#vehicle-model').append('<option value="Honda Accord (2008-2013)">Honda Accord (2008-2013)</option>');
                $('#vehicle-model').append('<option value="Honda Accord (2014+)">Honda Accord (2014+)</option>');
                $('#vehicle-model').append('<option value="Honda Accord (Sensing) (2017+)">Honda Accord (Sensing) (2017+)</option>');
                $('#vehicle-model').append('<option value="Honda Accord (2020+)">Honda Accord (2020+)</option>');
                $('#vehicle-model').append('<option value="Honda Accord (Sensing) (2020+)">Honda Accord (Sensing) (2020+)</option>');
                $('#vehicle-model').append('<option value="Honda CRZ">Honda CRZ</option>');
                $('#vehicle-model').append('<option value="Honda Civic FD (2005-2011)">Honda Civic FD (2005-2011)</option>');
                $('#vehicle-model').append('<option value="Honda Civic FB (2011-2016)">Honda Civic FB (2011-2016)</option>');
                $('#vehicle-model').append('<option value="Honda Civic FC (2016-2020)">Honda Civic FC (2016-2020)</option>');
                $('#vehicle-model').append('<option value="Honda Civic FK8 Type R (Sensing) (2022+)">Honda Civic FK8 Type R (Sensing) (2022+)</option>');
                $('#vehicle-model').append('<option value="Honda Civic FE (Sensing) (2021+)">Honda Civic FE (Sensing) (2021+)</option>');
                $('#vehicle-model').append('<option value="Honda Civic FE RS (Sensing) (2022+)">Honda Civic FE RS (Sensing) (2022+)</option>');
                $('#vehicle-model').append('<option value="Honda Civic FK8 Type R (Sensing) (2022+)">Honda Civic FK8 Type R (Sensing) (2022+)</option>');
                $('#vehicle-model').append('<option value="Honda Jazz (2006-2009)">Honda Jazz (2006-2009)</option>');
                $('#vehicle-model').append('<option value="Honda Jazz (2009-2014)">Honda Jazz (2009-2014)</option>');
                $('#vehicle-model').append('<option value="Honda Jazz (2014+)">Honda Jazz (2014+)</option>');
                $('#vehicle-model').append('<option value="Honda Stream (2000-2006)">Honda Stream (2000-2006)</option>');
                $('#vehicle-model').append('<option value="Honda Stream RN6 (2006+)">Honda Stream RN6 (2006+)</option>');
                $('#vehicle-model').append('<option value="Honda Odyssey RA6 (2002-2004)">Honda Odyssey RA6 (2002-2004)</option>');
                $('#vehicle-model').append('<option value="Honda Odyssey RB1-2 (2004-2008)">Honda Odyssey RB1-2 (2004-2008)</option>');
                $('#vehicle-model').append('<option value="Honda Odyssey RB3-4 (2008-2013)">Honda Odyssey RB3-4 (2008-2013)</option>');
                $('#vehicle-model').append('<option value="Honda Odyssey RC1 (2013+)">Honda Odyssey RC1 (2013+)</option>');
                $('#vehicle-model').append('<option value="Honda HRV (2013-2022)">Honda HRV (2013-2022)</option>');
                $('#vehicle-model').append('<option value="Honda HRV (Sensing) (2022+)">Honda HRV (Sensing) (2022+)</option>');
                $('#vehicle-model').append('<option value="Honda HRV Lanewatch Camera (2022+)">Honda HRV Lanewatch Camera (2022+)</option>');
                $('#vehicle-model').append('<option value="Honda BRV">Honda BRV</option>');
                $('#vehicle-model').append('<option value="Honda WR-V">Honda WR-V</option>');
                $('#vehicle-model').append('<option value="Honda WR-V Sensing">Honda WR-V Sensing</option>');
                $('#vehicle-model').append('<option value="Honda N-BOX (CHINA GLASS)">Honda N-BOX (CHINA GLASS)</option>');
                break;
            case 'Toyota':
                $('#vehicle-model').append('<option value="Toyota Vios (2002-2006)">Toyota Vios (2002-2006)</option>');
                $('#vehicle-model').append('<option value="Toyota Vios (2007-2014)">Toyota Vios (2007-2014)</option>');
                $('#vehicle-model').append('<option value="Toyota Vios (2014-2018)">Toyota Vios (2014-2018)</option>');
                $('#vehicle-model').append('<option value="Toyota Vios (2019+)">Toyota Vios (2019+)</option>');
                $('#vehicle-model').append('<option value="Toyota Vios Camera (2019+)">Toyota Vios Camera (2019+)</option>');
                $('#vehicle-model').append('<option value="Toyota Avanza">Toyota Avanza</option>');
                $('#vehicle-model').append('<option value="Toyota Avanza (2011-2020)">Toyota Avanza (2011-2020)</option>');
                $('#vehicle-model').append('<option value="Toyota Avanza (2021+)">Toyota Avanza (2021+)</option>');
                $('#vehicle-model').append('<option value="Toyota Unser (1998-2001)">Toyota Unser (1998-2001)</option>');
                $('#vehicle-model').append('<option value="Toyota Unser (2001-2005)">Toyota Unser (2001-2005)</option>');
                $('#vehicle-model').append('<option value="Toyota Camry CV35">Toyota Camry CV35</option>');
                $('#vehicle-model').append('<option value="Toyota Camry CV20">Toyota Camry CV20</option>');
                $('#vehicle-model').append('<option value="Toyota Camry CV31">Toyota Camry CV31</option>');
                $('#vehicle-model').append('<option value="Toyota Camry ACV40">Toyota Camry ACV40</option>');
                $('#vehicle-model').append('<option value="Toyota Camry ACV51">Toyota Camry ACV51</option>');
                $('#vehicle-model').append('<option value="Toyota Camry XV70">Toyota Camry XV70</option>');
                $('#vehicle-model').append('<option value="Toyota Camry XV70 (Sensor / Camera)">Toyota Camry XV70 (Sensor / Camera)</option>');
                $('#vehicle-model').append('<option value="Toyota Altis (2006-2008)">Toyota Altis (2006-2008)</option>');
                $('#vehicle-model').append('<option value="Toyota Altis (2009-2014)">Toyota Altis (2009-2014)</option>');
                $('#vehicle-model').append('<option value="Toyota Altis (2014-2019)">Toyota Altis (2014-2019)</option>');
                $('#vehicle-model').append('<option value="Toyota Altis (2019+)">Toyota Altis (2019+)</option>');
                $('#vehicle-model').append('<option value="Toyota Corolla Cross (2021+)">Toyota Corolla Cross (2021+)</option>');
                $('#vehicle-model').append('<option value="Toyota Rush">Toyota Rush</option>');
                $('#vehicle-model').append('<option value="Toyota Innova (2004-2015)">Toyota Innova (2004-2015)</option>');
                $('#vehicle-model').append('<option value="Toyota Innova (2019+)">Toyota Innova (2019+)</option>');
                $('#vehicle-model').append('<option value="Toyota RAV4 (2013-2019)">Toyota RAV4 (2013-2019)</option>');
                $('#vehicle-model').append('<option value="Toyota RAV4 (2020+)">Toyota RAV4 (2020+)</option>');
                $('#vehicle-model').append('<option value="Toyota Caldina">Toyota Caldina</option>');
                $('#vehicle-model').append('<option value="Toyota Hi-Lux (2004-2015)">Toyota Hi-Lux (2004-2015)</option>');
                $('#vehicle-model').append('<option value="Toyota Hi-Lux (2015+)">Toyota Hi-Lux (2015+)</option>');
                $('#vehicle-model').append('<option value="Toyota Fortuner (2004-2015)">Toyota Fortuner (2004-2015)</option>');
                $('#vehicle-model').append('<option value="Toyota Fortuner (2015-2020)">Toyota Fortuner (2015-2020)</option>');
                $('#vehicle-model').append('<option value="Toyota Fortuner (2021+)">Toyota Fortuner (2021+)</option>');
                $('#vehicle-model').append('<option value="Toyota Wish (2003-2009)">Toyota Wish (2003-2009)</option>');
                $('#vehicle-model').append('<option value="Toyota Wish (2012+)">Toyota Wish (2012+)</option>');
                $('#vehicle-model').append('<option value="Toyota Alphard ANH10 (2002-2008)">Toyota Alphard ANH10 (2002-2008)</option>');
                $('#vehicle-model').append('<option value="Toyota Vellfire AGH20 (2008-2015)">Toyota Vellfire AGH20 (2008-2015)</option>');
                $('#vehicle-model').append('<option value="Toyota Vellfire GGH30 (2015+)">Toyota Vellfire GGH30 (2015+)</option>');
                $('#vehicle-model').append('<option value="Toyota Harrier (2008-2011)">Toyota Harrier (2008-2011)</option>');
                $('#vehicle-model').append('<option value="Toyota Harrier (2004-2012)">Toyota Harrier (2004-2012)</option>');
                $('#vehicle-model').append('<option value="Toyota Harrier (2013-2020)">Toyota Harrier (2013-2020)</option>');
                $('#vehicle-model').append('<option value="Toyota Harrier (2021+)">Toyota Harrier (2021+)</option>');
                $('#vehicle-model').append('<option value="Toyota Prius">Toyota Prius</option>');
                $('#vehicle-model').append('<option value="Toyota Prius C">Toyota Prius C</option>');
                $('#vehicle-model').append('<option value="Toyota CHR">Toyota CHR</option>');
                $('#vehicle-model').append('<option value="Toyota Yaris (2019+)">Toyota Yaris (2019+)</option>');
                $('#vehicle-model').append('<option value="Toyota Estima ACR30 (2000-2005)">Toyota Estima ACR30 (2000-2005)</option>');
                $('#vehicle-model').append('<option value="Toyota Estima ACR50 (2006+)">Toyota Estima ACR50 (2006+)</option>');
                $('#vehicle-model').append('<option value="Toyota Sienta">Toyota Sienta</option>');
                $('#vehicle-model').append('<option value="Toyota 86">Toyota 86</option>');
                $('#vehicle-model').append('<option value="Toyota Mark X">Toyota Mark X</option>');
                $('#vehicle-model').append('<option value="Toyota Crown S210 (2012+)">Toyota Crown S210 (2012+)</option>');
                $('#vehicle-model').append('<option value="Toyota FJ Cruiser XJ10">Toyota FJ Cruiser XJ10</option>');
                $('#vehicle-model').append('<option value="Toyota Lexus">Toyota Lexus</option>');
                $('#vehicle-model').append('<option value="Toyota Landcruiser Prado J120 (2002-2009)">Toyota Landcruiser Prado J120 (2002-2009)</option>');
                $('#vehicle-model').append('<option value="Toyota Landcruiser Prado J150 (2009+)">Toyota Landcruiser Prado J150 (2009+)</option>');
                $('#vehicle-model').append('<option value="Toyota GR Supra">Toyota GR Supra</option>');
                $('#vehicle-model').append('<option value="Toyota Hi-Ace H200 (2004+)">Toyota Hi-Ace H200 (2004+)</option>');
                $('#vehicle-model').append('<option value="Toyota Veloz (2022+)">Toyota Veloz (2022+)</option>');
                break;
            case 'Nissan (Car)':
                $('#vehicle-model').append('<option value="Nissan Almera (2011-2020)">Nissan Almera (2011-2020)</option>');
                $('#vehicle-model').append('<option value="Nissan Almera (2021+)">Nissan Almera (2021+)</option>');
                $('#vehicle-model').append('<option value="Nissan Grand Livina">Nissan Grand Livina</option>');
                $('#vehicle-model').append('<option value="Nissan Teana J32 (2008–2013)">Nissan Teana J32 (2008–2013)</option>');
                $('#vehicle-model').append('<option value="Nissan Teana J33 (2013-2020)">Nissan Teana J33 (2013-2020)</option>');
                $('#vehicle-model').append('<option value="Nissan Sylphy">Nissan Sylphy</option>');
                $('#vehicle-model').append('<option value="Nissan X-trail T30 (2000-2007)">Nissan X-trail T30 (2000-2007)</option>');
                $('#vehicle-model').append('<option value="Nissan X-trail T31 (2007-2013)">Nissan X-trail T31 (2007-2013)</option>');
                $('#vehicle-model').append('<option value="Nissan X-trail T32 (2013+)">Nissan X-trail T32 (2013+)</option>');
                $('#vehicle-model').append('<option value="Nissan Sentra B14">Nissan Sentra B14</option>');
                $('#vehicle-model').append('<option value="Nissan Sentra N16">Nissan Sentra N16</option>');
                $('#vehicle-model').append('<option value="Nissan Frontier">Nissan Frontier</option>');
                $('#vehicle-model').append('<option value="Nissan Latio">Nissan Latio</option>');
                $('#vehicle-model').append('<option value="Nissan Cefiro A31">Nissan Cefiro A31</option>');
                $('#vehicle-model').append('<option value="Nissan Cefiro A32">Nissan Cefiro A32</option>');
                $('#vehicle-model').append('<option value="Nissan Cefiro A33">Nissan Cefiro A33</option>');
                $('#vehicle-model').append('<option value="Nissan Navara D22">Nissan Navara D22</option>');
                $('#vehicle-model').append('<option value="Nissan Navara D40">Nissan Navara D40</option>');
                $('#vehicle-model').append('<option value="Nissan Juke">Nissan Juke</option>');
                $('#vehicle-model').append('<option value="Nissan Elgrand">Nissan Elgrand</option>');
                $('#vehicle-model').append('<option value="Nissan Urvan E25">Nissan Urvan E25</option>');
                $('#vehicle-model').append('<option value="Nissan X-Gear">Nissan X-Gear</option>');
                $('#vehicle-model').append('<option value="Nissan Fairlady">Nissan Fairlady</option>');
                $('#vehicle-model').append('<option value="Nissan GTR R34">Nissan GTR R34</option>');
                $('#vehicle-model').append('<option value="Nissan GTR R35 (Sensor)">Nissan GTR R35 (Sensor)</option>');
                $('#vehicle-model').append('<option value="Nissan GTR R36">Nissan GTR R36</option>');
                $('#vehicle-model').append('<option value="Nissan GTR R35 (No Sensor)">Nissan GTR R35 (No Sensor)</option>');
                $('#vehicle-model').append('<option value="Nissan YU41 / UD41">Nissan YU41 / UD41</option>');
                $('#vehicle-model').append('<option value="Nissan Vanette C22">Nissan Vanette C22</option>');
                $('#vehicle-model').append('<option value="Nissan Serena C23">Nissan Serena C23</option>');
                $('#vehicle-model').append('<option value="Nissan Serena C24">Nissan Serena C24</option>');
                $('#vehicle-model').append('<option value="Nissan Serena C25">Nissan Serena C25</option>');
                $('#vehicle-model').append('<option value="Nissan Serena C26 Hybrid">Nissan Serena C26 Hybrid</option>');
                $('#vehicle-model').append('<option value="Nissan Serena C27">Nissan Serena C27</option>');
                $('#vehicle-model').append('<option value="Nissan Murano">Nissan Murano</option>');
                $('#vehicle-model').append('<option value="Nissan Kicks">Nissan Kicks</option>');
                break;
            case 'Mini Cooper':
                $('#vehicle-model').append('<option value="Mini Cooper R50/R52/R53 (2000-2006)">Mini Cooper R50/R52/R53 (2000-2006)</option>');
                $('#vehicle-model').append('<option value="Mini Clubman R55 (2007-2014)">Mini Clubman R55 (2007-2014)</option>');
                $('#vehicle-model').append('<option value="Mini Cooper R56 (2006-2015)">Mini Cooper R56 (2006-2015)</option>');
                $('#vehicle-model').append('<option value="Mini Clubman F54 (2015+)">Mini Clubman F54 (2015+)</option>');
                $('#vehicle-model').append('<option value="Mini Cooper F55(2013+)">Mini Cooper F55(2013+)</option>');
                $('#vehicle-model').append('<option value="Mini Countryman R60">Mini Countryman R60</option>');
                $('#vehicle-model').append('<option value="Mini Countryman F60">Mini Countryman F60</option>');
                break;
            case 'Mitsubishi':
                $('#vehicle-model').append('<option value="Mitsubishi L200">Mitsubishi L200</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Grandis">Mitsubishi Grandis</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Lancer 10">Mitsubishi Lancer 10</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Lancer 10 (sensor)">Mitsubishi Lancer 10 (sensor)</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Mirage">Mitsubishi Mirage</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Asx">Mitsubishi Asx</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Outlander (2005-2015)">Mitsubishi Outlander (2005-2015)</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Outlander (2016+)">Mitsubishi Outlander (2016+)</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Triton">Mitsubishi Triton</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Airtrek">Mitsubishi Airtrek</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Fuso">Mitsubishi Fuso</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Pajero">Mitsubishi Pajero</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Attrage">Mitsubishi Attrage</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Xpander (2021+)">Mitsubishi Xpander (2021+)</option>');
                break;
            case 'Peugeot':
                $('#vehicle-model').append('<option value="Peugeot 206">Peugeot 206</option>');
                $('#vehicle-model').append('<option value="Peugeot 207">Peugeot 207</option>');
                $('#vehicle-model').append('<option value="Peugeot 208">Peugeot 208</option>');
                $('#vehicle-model').append('<option value="Peugeot 308">Peugeot 308</option>');
                $('#vehicle-model').append('<option value="Peugeot 2008 (2022+)">Peugeot 2008 (2022+)</option>');
                $('#vehicle-model').append('<option value="Peugeot 3008 (2009-2017)">Peugeot 3008 (2009-2017)</option>');
                $('#vehicle-model').append('<option value="Peugeot 3008 (2018+)">Peugeot 3008 (2018+)</option>');
                $('#vehicle-model').append('<option value="Peugeot 5008 (2009-2017)">Peugeot 5008 (2009-2017)</option>');
                $('#vehicle-model').append('<option value="Peugeot 5008 (2018+)">Peugeot 5008 (2018+)</option>');
                $('#vehicle-model').append('<option value="Peugeot 407">Peugeot 407</option>');
                $('#vehicle-model').append('<option value="Peugeot 408">Peugeot 408</option>');
                $('#vehicle-model').append('<option value="Peugeot 508">Peugeot 508</option>');
                $('#vehicle-model').append('<option value="Peugeot Traveller">Peugeot Traveller</option>');
                break;
            case 'Volkswagen':
                $('#vehicle-model').append('<option value="Volkswagen Polo">Volkswagen Polo</option>');
                $('#vehicle-model').append('<option value="Volkswagen Polo Sedan">Volkswagen Polo Sedan</option>');
                $('#vehicle-model').append('<option value="Volkswagen Golf Mk5">Volkswagen Golf Mk5</option>');
                $('#vehicle-model').append('<option value="Volkswagen Golf Mk6">Volkswagen Golf Mk6</option>');
                $('#vehicle-model').append('<option value="Volkswagen Golf Mk7">Volkswagen Golf Mk7</option>');
                $('#vehicle-model').append('<option value="Volkswagen Golf Mk8 (2020+)">Volkswagen Golf Mk8 (2020+)</option>');
                $('#vehicle-model').append('<option value="Volkswagen Passat">Volkswagen Passat</option>');
                $('#vehicle-model').append('<option value="Volkswagen Passat CC">Volkswagen Passat CC</option>');
                $('#vehicle-model').append('<option value="Volkswagen Beetle">Volkswagen Beetle</option>');
                $('#vehicle-model').append('<option value="Volkswagen Scirocco">Volkswagen Scirocco</option>');
                $('#vehicle-model').append('<option value="Volkswagen Jetta">Volkswagen Jetta</option>');
                $('#vehicle-model').append('<option value="Volkswagen Touran">Volkswagen Touran</option>');
                $('#vehicle-model').append('<option value="Volkswagen Tiguan">Volkswagen Tiguan</option>');
                $('#vehicle-model').append('<option value="Volkswagen Sharan">Volkswagen Sharan</option>');
                $('#vehicle-model').append('<option value="Volkswagen Vento">Volkswagen Vento</option>');
                $('#vehicle-model').append('<option value="Volkswagen Arteon">Volkswagen Arteon</option>');
                break;
            case 'Subaru':
                $('#vehicle-model').append('<option value="Subaru Forester">Subaru Forester</option>');
                $('#vehicle-model').append('<option value="Subaru XV">Subaru XV</option>');
                $('#vehicle-model').append('<option value="Subaru Forester (Sensor)">Subaru Forester (Sensor)</option>');
                $('#vehicle-model').append('<option value="Subaru Levrog VM (2014-2019)">Subaru Levrog VM (2014-2019)</option>');
                $('#vehicle-model').append('<option value="Subaru Levrog VN (2020+)">Subaru Levrog VN (2020+)</option>');
                break;
            case 'Ssangyong':
                $('#vehicle-model').append('<option value="Ssangyong Rexton">Ssangyong Rexton</option>');
                $('#vehicle-model').append('<option value="Ssangyong Kyron">Ssangyong Kyron</option>');
                $('#vehicle-model').append('<option value="Ssangyong Actyon">Ssangyong Actyon</option>');
                $('#vehicle-model').append('<option value="Ssangyong Musso">Ssangyong Musso</option>');
                break;
            case 'Kia':
                $('#vehicle-model').append('<option value="Kia Optima">Kia Optima</option>');
                $('#vehicle-model').append('<option value="Kia Picanto">Kia Picanto</option>');
                $('#vehicle-model').append('<option value="Kia Spectra / Kia Sephia">Kia Spectra / Kia Sephia</option>');
                $('#vehicle-model').append('<option value="Kia Sportage">Kia Sportage</option>');
                $('#vehicle-model').append('<option value="Kia / Naza Forte">Kia / Naza Forte</option>');
                $('#vehicle-model').append('<option value="Kia Rio">Kia Rio</option>');
                $('#vehicle-model').append('<option value="Naza Sutera">Naza Sutera</option>');
                $('#vehicle-model').append('<option value="Kia Optima K5">Kia Optima K5</option>');
                $('#vehicle-model').append('<option value="Kia Cerato K3">Kia Cerato K3</option>');
                $('#vehicle-model').append('<option value="Kia Carnival (2016-present)">Kia Carnival (2016-present)</option>');
                $('#vehicle-model').append('<option value="Kia Carnival (2022+)">Kia Carnival (2022+)</option>');
                break;
            case 'Isuzu (Car)':
                $('#vehicle-model').append('<option value="Isuzu D-max MU-7 (2005-2012)">Isuzu D-max MU-7 (2005-2012)</option>');
                $('#vehicle-model').append('<option value="Isuzu D-max RT50 (2012-2019)">Isuzu D-max RT50 (2012-2019)</option>');
                $('#vehicle-model').append('<option value="Isuzu D-max RG01(2021+)">Isuzu D-max RG01(2021+)</option>');
                break;
            case 'Suzuki (Car)':
                $('#vehicle-model').append('<option value="Suzuki Swift (2004-2010)">Suzuki Swift (2004-2010)</option>');
                $('#vehicle-model').append('<option value="Suzuki Swift (2010-2017)">Suzuki Swift (2010-2017)</option>');
                $('#vehicle-model').append('<option value="Suzuki Swift (2020+)">Suzuki Swift (2020+)</option>');
                $('#vehicle-model').append('<option value="Suzuki APV">Suzuki APV</option>');
                $('#vehicle-model').append('<option value="Suzuki SX4">Suzuki SX4</option>');
                $('#vehicle-model').append('<option value="Suzuki SX4 S-Cross">Suzuki SX4 S-Cross</option>');
                $('#vehicle-model').append('<option value="Suzuki Alto">Suzuki Alto</option>');
                $('#vehicle-model').append('<option value="Suzuki Jimny (2019+)">Suzuki Jimny (2019+)</option>');
                break;
            case 'Mazda':
                $('#vehicle-model').append('<option value="Mazda 2">Mazda 2</option>');
                $('#vehicle-model').append('<option value="Mazda 3 (2008-2013)">Mazda 3 (2008-2013)</option>');
                $('#vehicle-model').append('<option value="Mazda 3 (2014+)">Mazda 3 (2014+)</option>');
                $('#vehicle-model').append('<option value="Mazda CX-30 (2019+)">Mazda CX-30 (2019+)</option>');
                $('#vehicle-model').append('<option value="Mazda 5">Mazda 5</option>');
                $('#vehicle-model').append('<option value="Mazda 6">Mazda 6</option>');
                $('#vehicle-model').append('<option value="Mazda CX3">Mazda CX3</option>');
                $('#vehicle-model').append('<option value="Mazda CX5 (2012-2017)">Mazda CX5 (2012-2017)</option>');
                $('#vehicle-model').append('<option value="Mazda CX5 Auto Brek (2017+)">Mazda CX5 Auto Brek (2017+)</option>');
                $('#vehicle-model').append('<option value="Mazda CX5 (2017+)">Mazda CX5 (2017+)</option>');
                $('#vehicle-model').append('<option value="Mazda CX7">Mazda CX7</option>');
                $('#vehicle-model').append('<option value="Mazda CX9">Mazda CX9</option>');
                $('#vehicle-model').append('<option value="Mazda MPV LW (1999-2006)">Mazda MPV LW (1999-2006)</option>');
                $('#vehicle-model').append('<option value="Mazda MPV LY (2006-2016)">Mazda MPV LY (2006-2016)</option>');
                $('#vehicle-model').append('<option value="Mazda RX8">Mazda RX8</option>');
                $('#vehicle-model').append('<option value="Mazda CX8 (2021+)">Mazda CX8 (2021+)</option>');
                $('#vehicle-model').append('<option value="Mazda Biante">Mazda Biante</option>');
                $('#vehicle-model').append('<option value="Mazda BT50">Mazda BT50</option>');
                break;
            case 'McLaren':
                $('#vehicle-model').append('<option value="McLaren 570S">McLaren 570S</option>');
                $('#vehicle-model').append('<option value="McLaren 720S">McLaren 720S</option>');
                break;
            case 'Chevrolet':
                $('#vehicle-model').append('<option value="Chevrolet Malibu">Chevrolet Malibu</option>');
                $('#vehicle-model').append('<option value="Chevrolet Cruze">Chevrolet Cruze</option>');
                $('#vehicle-model').append('<option value="Chevrolet Nabira">Chevrolet Nabira</option>');
                $('#vehicle-model').append('<option value="Chevrolet Orlando">Chevrolet Orlando</option>');
                $('#vehicle-model').append('<option value="Chevrolet Colorado">Chevrolet Colorado</option>');
                $('#vehicle-model').append('<option value="Chevrolet Sonic">Chevrolet Sonic</option>');
                break;
            case 'Hyundai':
                $('#vehicle-model').append('<option value="Hyundai Accent">Hyundai Accent</option>');
                $('#vehicle-model').append('<option value="Hyundai i10">Hyundai i10</option>');
                $('#vehicle-model').append('<option value="Hyundai Starex">Hyundai Starex</option>');
                $('#vehicle-model').append('<option value="Hyundai Elantra (2011-2016)">Hyundai Elantra (2011-2016)</option>');
                $('#vehicle-model').append('<option value="Hyundai Elantra (2016+)">Hyundai Elantra (2016+)</option>');
                $('#vehicle-model').append('<option value="Hyundai Getz">Hyundai Getz</option>');
                $('#vehicle-model').append('<option value="Hyundai Matrix">Hyundai Matrix</option>');
                $('#vehicle-model').append('<option value="Hyundai Atos">Hyundai Atos</option>');
                $('#vehicle-model').append('<option value="Hyundai Sonata EF">Hyundai Sonata EF</option>');
                $('#vehicle-model').append('<option value="Hyundai Sonata NF">Hyundai Sonata NF</option>');
                $('#vehicle-model').append('<option value="Hyundai Sonata YF">Hyundai Sonata YF</option>');
                $('#vehicle-model').append('<option value="Hyundai Trajet">Hyundai Trajet</option>');
                $('#vehicle-model').append('<option value="Hyundai Tucson">Hyundai Tucson</option>');
                $('#vehicle-model').append('<option value="Hyundai SantaFE 06-2012 (Sensor)">Hyundai SantaFE 06-2012 (Sensor)</option>');
                $('#vehicle-model').append('<option value="Hyundai SantaFe 06-2012 (No Sensor)">Hyundai SantaFe 06-2012 (No Sensor)</option>');
                $('#vehicle-model').append('<option value="Hyundai Ioniq (No Sensor)">Hyundai Ioniq (No Sensor)</option>');
                $('#vehicle-model').append('<option value="Hyundai Ioniq (Sensor)">Hyundai Ioniq (Sensor)</option>');
                $('#vehicle-model').append('<option value="Hyundai Kona">Hyundai Kona</option>');
                $('#vehicle-model').append('<option value="Hyundai Staria">Hyundai Staria</option>');
                break;
            case 'BMW (Car)':
                $('#vehicle-model').append('<option value="BMW E90 3 SERIES">BMW E90 3 SERIES</option>');
                $('#vehicle-model').append('<option value="BMW F30 3 SERIES">BMW F30 3 SERIES</option>');
                $('#vehicle-model').append('<option value="BMW G20 3 SERIES (2018+)">BMW G20 3 SERIES (2018+)</option>');
                $('#vehicle-model').append('<option value="BMW F32 4 SERIES (2014-2019)">BMW F32 4 SERIES (2014-2019)</option>');
                $('#vehicle-model').append('<option value="BMW G22 4 SERIES (2020+)">BMW G22 4 SERIES (2020+)</option>');
                $('#vehicle-model').append('<option value="BMW E39 5 SERIES">BMW E39 5 SERIES</option>');
                $('#vehicle-model').append('<option value="BMW E60 5 SERIES">BMW E60 5 SERIES</option>');
                $('#vehicle-model').append('<option value="BMW F10 5 SERIES">BMW F10 5 SERIES</option>');
                $('#vehicle-model').append('<option value="BMW G30 5 SERIES (2016+)">BMW G30 5 SERIES (2016+)</option>');
                $('#vehicle-model').append('<option value="BMW E63 6 SERIES (2004-2011)">BMW E63 6 SERIES (2004-2011)</option>');
                $('#vehicle-model').append('<option value="BMW F06 6 SERIES (2012-2017)">BMW F06 6 SERIES (2012-2017)</option>');
                $('#vehicle-model').append('<option value="BMW G32 6 SERIES (2018+)">BMW G32 6 SERIES (2018+)</option>');
                $('#vehicle-model').append('<option value="BMW E65 7 SERIES (2001-2008)">BMW E65 7 SERIES (2001-2008)</option>');
                $('#vehicle-model').append('<option value="BMW F01 7 SERIES (2009-2014)">BMW F01 7 SERIES (2009-2014)</option>');
                $('#vehicle-model').append('<option value="BMW G11 7 SERIES (2015-2021)">BMW G11 7 SERIES (2015-2021)</option>');
                $('#vehicle-model').append('<option value="BMW G70 7 SERIES (2022+)">BMW G70 7 SERIES (2022+)</option>');
                $('#vehicle-model').append('<option value="BMW G14 8 SERIES (2018+)">BMW G14 8 SERIES (2018+)</option>');
                $('#vehicle-model').append('<option value="BMW X1 E84 (2009-2015)">BMW X1 E84 (2009-2015)</option>');
                $('#vehicle-model').append('<option value="BMW X1 F48 (2015+)">BMW X1 F48 (2015+)</option>');
                $('#vehicle-model').append('<option value="BMW X2 F39 (2018+)">BMW X2 F39 (2018+)</option>');
                $('#vehicle-model').append('<option value="BMW X3 E83 (2003-2009)">BMW X3 E83 (2003-2009)</option>');
                $('#vehicle-model').append('<option value="BMW X3 F25 (2010-2016)">BMW X3 F25 (2010-2016)</option>');
                $('#vehicle-model').append('<option value="BMW X3 G01 (2018+)">BMW X3 G01 (2018+)</option>');
                $('#vehicle-model').append('<option value="BMW X4 F26 (2014-2018)">BMW X4 F26 (2014-2018)</option>');
                $('#vehicle-model').append('<option value="BMW X4 G02 (2018+)">BMW X4 G02 (2018+)</option>');
                $('#vehicle-model').append('<option value="BMW X5 E70 (2006-2013)">BMW X5 E70 (2006-2013)</option>');
                $('#vehicle-model').append('<option value="BMW X5 F15/F85 (2014-2018)">BMW X5 F15/F85 (2014-2018)</option>');
                $('#vehicle-model').append('<option value="BMW X5 G05 (2019+)">BMW X5 G05 (2019+)</option>');
                $('#vehicle-model').append('<option value="BMW X6 E71 (2008-2014)">BMW X6 E71 (2008-2014)</option>');
                $('#vehicle-model').append('<option value="BMW X6 F16 (2015-2019)">BMW X6 F16 (2015-2019)</option>');
                $('#vehicle-model').append('<option value="BMW X6 G06 (2020+)">BMW X6 G06 (2020+)</option>');
                $('#vehicle-model').append('<option value="BMW X7 G07 (2018+)">BMW X7 G07 (2018+)</option>');
                $('#vehicle-model').append('<option value="BMW Z4 E89 (2009-2017)">BMW Z4 E89 (2009-2017)</option>');
                $('#vehicle-model').append('<option value="BMW Z4 G29 (2018+)">BMW Z4 G29 (2018+)</option>');
                $('#vehicle-model').append('<option value="BMW I8">BMW I8</option>');
                $('#vehicle-model').append('<option value="BMW iX3">BMW iX3</option>');
                break;
            case 'Chery':
                $('#vehicle-model').append('<option value="Chery Easter">Chery Easter</option>');
                break;
            case 'Volvo':
                $('#vehicle-model').append('<option value="Volvo V40">Volvo V40</option>');
                $('#vehicle-model').append('<option value="Volvo V90">Volvo V90</option>');
                $('#vehicle-model').append('<option value="Volvo S60">Volvo S60</option>');
                $('#vehicle-model').append('<option value="Volvo S90">Volvo S90</option>');
                $('#vehicle-model').append('<option value="Volvo XC40">Volvo XC40</option>');
                $('#vehicle-model').append('<option value="Volvo XC60 (2008-2017)">Volvo XC60 (2008-2017)</option>');
                $('#vehicle-model').append('<option value="Volvo XC60 (2018-2021)">Volvo XC60 (2018-2021)</option>');
                $('#vehicle-model').append('<option value="Volvo XC60 (2022+)">Volvo XC60 (2022+)</option>');
                $('#vehicle-model').append('<option value="Volvo S40">Volvo S40</option>');
                $('#vehicle-model').append('<option value="Volvo S80">Volvo S80</option>');
                $('#vehicle-model').append('<option value="Volvo XC90">Volvo XC90</option>');
                $('#vehicle-model').append('<option value="Volvo S90">Volvo S90</option>');
                break;
            case 'Ford':
                $('#vehicle-model').append('<option value="Ford Fiesta">Ford Fiesta</option>');
                $('#vehicle-model').append('<option value="Ford Focus">Ford Focus</option>');
                $('#vehicle-model').append('<option value="Ford Mondeo">Ford Mondeo</option>');
                $('#vehicle-model').append('<option value="Ford S-MAX">Ford S-MAX</option>');
                $('#vehicle-model').append('<option value="Ford Focus (4 Sensors)">Ford Focus (4 Sensors)</option>');
                $('#vehicle-model').append('<option value="Ford Ranger">Ford Ranger</option>');
                $('#vehicle-model').append('<option value="Ford Ranger (Sensor)">Ford Ranger (Sensor)</option>');
                $('#vehicle-model').append('<option value="Ford Everest">Ford Everest</option>');
                $('#vehicle-model').append('<option value="Ford Kuga">Ford Kuga</option>');
                $('#vehicle-model').append('<option value="Ford Ecosport">Ford Ecosport</option>');
                $('#vehicle-model').append('<option value="Ford Mustang">Ford Mustang</option>');
                break;
            case 'Mercedes-Benz':
                $('#vehicle-model').append('<option value="Mercedes S Class W220 (1999-2005)">Mercedes S Class W220 (1999-2005)</option>');
                $('#vehicle-model').append('<option value="Mercedes S Class W221 (2006-2012)">Mercedes S Class W221 (2006-2012)</option>');
                $('#vehicle-model').append('<option value="Mercedes S Class W222 (2013+)">Mercedes S Class W222 (2013+)</option>');
                $('#vehicle-model').append('<option value="Mercedes A Class W169 (2002-2017)">Mercedes A Class W169 (2002-2017)</option>');
                $('#vehicle-model').append('<option value="Mercedes A Class W177 (2018+)">Mercedes A Class W177 (2018+)</option>');
                $('#vehicle-model').append('<option value="Mercedes B Class W245 (2005-2011)">Mercedes B Class W245 (2005-2011)</option>');
                $('#vehicle-model').append('<option value="Mercedes B Class W246 (2012+)">Mercedes B Class W246 (2012+)</option>');
                $('#vehicle-model').append('<option value="Mercedes C Class W203 (2001-2007)">Mercedes C Class W203 (2001-2007)</option>');
                $('#vehicle-model').append('<option value="Mercedes C Class W204 (2008-2013)">Mercedes C Class W204 (2008-2013)</option>');
                $('#vehicle-model').append('<option value="Mercedes C Class W205 (2014-2020)">Mercedes C Class W205 (2014-2020)</option>');
                $('#vehicle-model').append('<option value="Mercedes C Class W206 (2021+)">Mercedes C Class W206 (2021+)</option>');
                $('#vehicle-model').append('<option value="Mercedes E Class W210 (1995-2001)">Mercedes E Class W210 (1995-2001)</option>');
                $('#vehicle-model').append('<option value="Mercedes E Class W211 (2002-2008)">Mercedes E Class W211 (2002-2008)</option>');
                $('#vehicle-model').append('<option value="Mercedes E Class W212 (2009-2016)">Mercedes E Class W212 (2009-2016)</option>');
                $('#vehicle-model').append('<option value="Mercedes E Class W213 (2017+)">Mercedes E Class W213 (2017+)</option>');
                $('#vehicle-model').append('<option value="Mercedes CLS W218 (2004-2010)">Mercedes CLS W218 (2004-2010)</option>');
                $('#vehicle-model').append('<option value="Mercedes CLS W219 (2011-2017)">Mercedes CLS W219 (2011-2017)</option>');
                $('#vehicle-model').append('<option value="Mercedes GLC X253 (2011-2019)">Mercedes GLC X253 (2011-2019)</option>');
                $('#vehicle-model').append('<option value="Mercedes M-GLASS W163 (1997-2005)">Mercedes M-GLASS W163 (1997-2005)</option>');
                $('#vehicle-model').append('<option value="Mercedes M-GLASS W164 (2005-2011)">Mercedes M-GLASS W164 (2005-2011)</option>');
                $('#vehicle-model').append('<option value="Mercedes GLE (2005-2011)">Mercedes GLE (2005-2011)</option>');
                $('#vehicle-model').append('<option value="Mercedes GLE (2019+)">Mercedes GLE (2019+)</option>');
                $('#vehicle-model').append('<option value="Mercedes SLK (2004-2010)">Mercedes SLK (2004-2010)</option>');
                $('#vehicle-model').append('<option value="Mercedes SLK (2011-2019)">Mercedes SLK (2011-2019)</option>');
                $('#vehicle-model').append('<option value="Mercedes CLA C117 (2013-2018)">Mercedes CLA C117 (2013-2018)</option>');
                $('#vehicle-model').append('<option value="Mercedes CLA C118 (2019+)">Mercedes CLA C118 (2019+)</option>');
                $('#vehicle-model').append('<option value="Mercedes AMG CLA 45 (2013+)">Mercedes AMG CLA 45 (2013+)</option>');
                $('#vehicle-model').append('<option value="Mercedes Spinter W903 (2013+)">Mercedes Spinter W903 (2013+)</option>');
                $('#vehicle-model').append('<option value="Mercedes GLA C117">Mercedes GLA C117</option>');
                $('#vehicle-model').append('<option value="Mercedes G-CLASS W461">Mercedes G-CLASS W461</option>');
                $('#vehicle-model').append('<option value="Mercedes G-CLASS W463">Mercedes G-CLASS W463</option>');
                break;
            case 'Lexus':
                $('#vehicle-model').append('<option value="Lexus IS XE10 (2013+)">Lexus IS XE10 (2013+)</option>');
                $('#vehicle-model').append('<option value="Lexus LS XF40 (2006-2017)">Lexus LS XF40 (2006-2017)</option>');
                $('#vehicle-model').append('<option value="Lexus LS XF50 (2017+)">Lexus LS XF50 (2017+)</option>');
                $('#vehicle-model').append('<option value="Lexus ES XV60 (2012-2017)">Lexus ES XV60 (2012-2017)</option>');
                $('#vehicle-model').append('<option value="Lexus ES XZ10 (2018+)">Lexus ES XZ10 (2018+)</option>');
                $('#vehicle-model').append('<option value="Lexus NX AZ10 (2014+)">Lexus NX AZ10 (2014+)</option>');
                $('#vehicle-model').append('<option value="Lexus RX AL20 (2015+)">Lexus RX AL20 (2015+)</option>');
                $('#vehicle-model').append('<option value="Lexus CT ZWA10">Lexus CT ZWA10</option>');
                $('#vehicle-model').append('<option value="Lexus LX J200 (2007+)">Lexus LX J200 (2007+)</option>');
                $('#vehicle-model').append('<option value="Lexus UX MZAH10 (2020+)">Lexus UX MZAH10 (2020+)</option>');
                $('#vehicle-model').append('<option value="Lexus GS L10 (2010+)">Lexus GS L10 (2010+)</option>');
                $('#vehicle-model').append('<option value="Lexus LM350 (2021+)">Lexus LM350 (2021+)</option>');
                break;
            case 'Rolls Royce':
                $('#vehicle-model').append('<option value="Rolls Royce Ghost (2014)">Rolls Royce Ghost (2014)</option>');
                $('#vehicle-model').append('<option value="Rolls Royce Ghost (2016-present)">Rolls Royce Ghost (2016-present)</option>');
                $('#vehicle-model').append('<option value="Rolls Royce Phantom">Rolls Royce Phantom</option>');
                break;
            case 'Bentley':
                $('#vehicle-model').append('<option value="Bentley Flying Spur">Bentley Flying Spur</option>');
                $('#vehicle-model').append('<option value="Bentley Bentayga">Bentley Bentayga</option>');
                break;
            case 'Porsche':
                $('#vehicle-model').append('<option value="Porsche Cayanne (2002-2009)">Porsche Cayanne (2002-2009)</option>');
                $('#vehicle-model').append('<option value="Porsche Cayanne (2010-2017)">Porsche Cayanne (2010-2017)</option>');
                $('#vehicle-model').append('<option value="Porsche Cayanne (2018+)">Porsche Cayanne (2018+)</option>');
                $('#vehicle-model').append('<option value="Porsche Macan">Porsche Macan</option>');
                $('#vehicle-model').append('<option value="Porsche Macan (Camera)">Porsche Macan (Camera)</option>');
                $('#vehicle-model').append('<option value="Porsche 911 Carerra (1997-2006)">Porsche 911 Carerra (1997-2006)</option>');
                $('#vehicle-model').append('<option value="Porsche 911 Carerra (2005-2012)">Porsche 911 Carerra (2005-2012)</option>');
                $('#vehicle-model').append('<option value="Porsche 911 Carerra S (2012-2019)">Porsche 911 Carerra S (2012-2019)</option>');
                $('#vehicle-model').append('<option value="Porsche Boxster (2012-2016)">Porsche Boxster (2012-2016)</option>');
                $('#vehicle-model').append('<option value="Porsche Boxster (2017+)">Porsche Boxster (2017+)</option>');
                $('#vehicle-model').append('<option value="Porsche Cayman (2006-2012)">Porsche Cayman (2006-2012)</option>');
                $('#vehicle-model').append('<option value="Porsche Cayman (2013-2016)">Porsche Cayman (2013-2016)</option>');
                $('#vehicle-model').append('<option value="Porsche 718 Cayman (2017+)">Porsche 718 Cayman (2017+)</option>');
                $('#vehicle-model').append('<option value="Porsche Panamera (2009-2015)">Porsche Panamera (2009-2015)</option>');
                $('#vehicle-model').append('<option value="Porsche Panamera (2016+)">Porsche Panamera (2016+)</option>');
                break;
            case 'Jaguar':
                $('#vehicle-model').append('<option value="Jaguar XF">Jaguar XF</option>');
                $('#vehicle-model').append('<option value="Jaguar XJL">Jaguar XJL</option>');
                break;
            case 'Landrover Range Rover':
                $('#vehicle-model').append('<option value="Range Rover Voque P525 (2019+)">Range Rover Voque P525 (2019+)</option>');
                $('#vehicle-model').append('<option value="Range Rover Sport HSE P525 (2015+)">Range Rover Sport HSE P525 (2015+)</option>');
                $('#vehicle-model').append('<option value="Range Rover Sport Autobiography P525 (2020+)">Range Rover Sport Autobiography P525 (2020+)</option>');
                $('#vehicle-model').append('<option value="Range Rover Sport L320 (2003-2013)">Range Rover Sport L320 (2003-2013)</option>');
                $('#vehicle-model').append('<option value="Range Rover Sport L494 (2014+)">Range Rover Sport L494 (2014+)</option>');
                $('#vehicle-model').append('<option value="Range Rover Evoque L538 (2012-2019)">Range Rover Evoque L538 (2012-2019)</option>');
                $('#vehicle-model').append('<option value="Range Rover Evoque L538 (2012-2019)*S">Range Rover Evoque L538 (2012-2019)*S</option>');
                $('#vehicle-model').append('<option value="Range Rover Evoque L551 (2020+)">Range Rover Evoque L551 (2020+)</option>');
                $('#vehicle-model').append('<option value="Range Rover Freelander (1997-2006)">Range Rover Freelander (1997-2006)</option>');
                $('#vehicle-model').append('<option value="Range Rover Freelander2 L359 (2006-2015)">Range Rover Freelander2 L359 (2006-2015)</option>');
                $('#vehicle-model').append('<option value="Range Rover Defender 110">Range Rover Defender 110</option>');
                $('#vehicle-model').append('<option value="Range Rover Defender L663 (2020+)">Range Rover Defender L663 (2020+)</option>');
                $('#vehicle-model').append('<option value="Range Rover Velar (2018+)">Range Rover Velar (2018+)</option>');
                $('#vehicle-model').append('<option value="Range Rover Velar (2018+)*S">Range Rover Velar (2018+)*S</option>');
                $('#vehicle-model').append('<option value="Range Rover Discovery Sport (2020+)">Range Rover Discovery Sport (2020+)</option>');
                break;
            case 'Infiniti':
                $('#vehicle-model').append('<option value="Infiniti Q50">Infiniti Q50</option>');
                $('#vehicle-model').append('<option value="Infiniti Q60">Infiniti Q60</option>');
                $('#vehicle-model').append('<option value="Infiniti Q70">Infiniti Q70</option>');
                $('#vehicle-model').append('<option value="Infiniti QX50">Infiniti QX50</option>');
                $('#vehicle-model').append('<option value="Infiniti QX70">Infiniti QX70</option>');
                $('#vehicle-model').append('<option value="Infiniti QX80">Infiniti QX80</option>');
                break;
            case 'Audi':
                $('#vehicle-model').append('<option value="Audi A4 B5">Audi A4 B5</option>');
                $('#vehicle-model').append('<option value="Audi A4 B6">Audi A4 B6</option>');
                $('#vehicle-model').append('<option value="Audi A4 B7">Audi A4 B7</option>');
                $('#vehicle-model').append('<option value="Audi A4 B8">Audi A4 B8</option>');
                $('#vehicle-model').append('<option value="Audi S5">Audi S5</option>');
                $('#vehicle-model').append('<option value="Audi RS5">Audi RS5</option>');
                $('#vehicle-model').append('<option value="Audi A6 C5">Audi A6 C5</option>');
                $('#vehicle-model').append('<option value="Audi A6 C6">Audi A6 C6</option>');
                $('#vehicle-model').append('<option value="Audi A6 C7">Audi A6 C7</option>');
                $('#vehicle-model').append('<option value="Audi A6 C8 (2018-New)">Audi A6 C8 (2018-New)</option>');
                $('#vehicle-model').append('<option value="Audi A7">Audi A7</option>');
                $('#vehicle-model').append('<option value="Audi A8 (2002-2009)">Audi A8 (2002-2009)</option>');
                $('#vehicle-model').append('<option value="Audi A8 (2011-2017)">Audi A8 (2011-2017)</option>');
                $('#vehicle-model').append('<option value="Audi A8 (2018-New)">Audi A8 (2018-New)</option>');
                $('#vehicle-model').append('<option value="Audi R8 (2006-2015)">Audi R8 (2006-2015)</option>');
                $('#vehicle-model').append('<option value="Audi R8 (2015-New)">Audi R8 (2015-New)</option>');
                $('#vehicle-model').append('<option value="Audi Q3">Audi Q3</option>');
                $('#vehicle-model').append('<option value="Audi Q5">Audi Q5</option>');
                $('#vehicle-model').append('<option value="Audi Q7">Audi Q7</option>');
                $('#vehicle-model').append('<option value="Audi S4 B6">Audi S4 B6</option>');
                $('#vehicle-model').append('<option value="Audi S4 B7">Audi S4 B7</option>');
                $('#vehicle-model').append('<option value="Audi S4 B8">Audi S4 B8</option>');
                $('#vehicle-model').append('<option value="Audi S4 B9">Audi S4 B9</option>');
                $('#vehicle-model').append('<option value="Audi TT">Audi TT</option>');
                $('#vehicle-model').append('<option value="Audi TTS">Audi TTS</option>');
                $('#vehicle-model').append('<option value="Audi TTRS">Audi TTRS</option>');
                break;
            case 'Citroen':
                $('#vehicle-model').append('<option value="Citroen C1 (2005-2014)">Citroen C1 (2005-2014)</option>');
                $('#vehicle-model').append('<option value="Citroen C1 (2014+)">Citroen C1 (2014+)</option>');
                $('#vehicle-model').append('<option value="Citroen C2">Citroen C2</option>');
                $('#vehicle-model').append('<option value="Citroen C3 (2002-2008)">Citroen C3 (2002-2008)</option>');
                $('#vehicle-model').append('<option value="Citroen C3 (2009-2015)">Citroen C3 (2009-2015)</option>');
                $('#vehicle-model').append('<option value="Citroen C3 (2016+)">Citroen C3 (2016+)</option>');
                $('#vehicle-model').append('<option value="Citroen C4 (2010-2019)">Citroen C4 (2010-2019)</option>');
                $('#vehicle-model').append('<option value="Citroen C5 (2001-2007)">Citroen C5 (2001-2007)</option>');
                $('#vehicle-model').append('<option value="Citroen Jumper">Citroen Jumper</option>');
                $('#vehicle-model').append('<option value="Citroen Jumpy">Citroen Jumpy</option>');
                $('#vehicle-model').append('<option value="Citroen Berlingo B9 (2008+)">Citroen Berlingo B9 (2008+)</option>');
                $('#vehicle-model').append('<option value="Citroen DS3">Citroen DS3</option>');
                $('#vehicle-model').append('<option value="Citroen DS4 (2016-2018)">Citroen DS4 (2016-2018)</option>');
                $('#vehicle-model').append('<option value="Citroen DS5">Citroen DS5</option>');
                $('#vehicle-model').append('<option value="Citroen DS6 (2014+)">Citroen DS6 (2014+)</option>');
                $('#vehicle-model').append('<option value="Citroen DS7">Citroen DS7</option>');
                $('#vehicle-model').append('<option value="Citroen C8">Citroen C8</option>');
                break;

                //motorcycle 
            case 'Yamaha':
                $('#vehicle-model').append('<option value="Yamaha NVX">Yamaha NVX</option>');
                $('#vehicle-model').append('<option value="Yamaha NMAX">Yamaha NMAX</option>');
                $('#vehicle-model').append('<option value="Yamaha Y15ZR">Yamaha Y15ZR</option>');
                $('#vehicle-model').append('<option value="Yamaha Y16ZR">Yamaha Y16ZR</option>');
                $('#vehicle-model').append('<option value="Yamaha Ego Avantiz">Yamaha Ego Avantiz</option>');
                $('#vehicle-model').append('<option value="Yamaha XMax 250">Yamaha XMax 250</option>');
                $('#vehicle-model').append('<option value="Yamaha 135LC Fi">Yamaha 135LC Fi</option>');
                $('#vehicle-model').append('<option value="Yamaha YZF-R15">Yamaha YZF-R15</option>');
                $('#vehicle-model').append('<option value="Yamaha MT-15">Yamaha MT-15</option>');
                $('#vehicle-model').append('<option value="Yamaha MT-25">Yamaha MT-25</option>');
                $('#vehicle-model').append('<option value="Yamaha YZF-R25">Yamaha YZF-R25</option>');
                $('#vehicle-model').append('<option value="Yamaha Ego Gear">Yamaha Ego Gear</option>');
                $('#vehicle-model').append('<option value="Yamaha Lagenda 115Z">Yamaha Lagenda 115Z</option>');
                $('#vehicle-model').append('<option value="Yamaha TMax">Yamaha TMax</option>');
                $('#vehicle-model').append('<option value="Yamaha MT-09">Yamaha MT-09</option>');
                $('#vehicle-model').append('<option value="Yamaha R15M">Yamaha R15M</option>');
                $('#vehicle-model').append('<option value="Yamaha MT-07">Yamaha MT-07</option>');
                $('#vehicle-model').append('<option value="Yamaha EZ115">Yamaha EZ115</option>');
                $('#vehicle-model').append('<option value="Yamaha Tracer 900 GT">Yamaha Tracer 900 GT</option>');
                $('#vehicle-model').append('<option value="Yamaha Y16ZR Doxou">Yamaha Y16ZR Doxou</option>');
                $('#vehicle-model').append('<option value="Yamaha Tenere 700">Yamaha Tenere 700</option>');
                break;
            case 'Honda (Motor)':
                $('#vehicle-model').append('<option value="Honda RS-X">Honda RS-X</option>');
                $('#vehicle-model').append('<option value="Honda CBR250RR">Honda CBR250RR</option>');
                $('#vehicle-model').append('<option value="Honda CBR150R">Honda CBR150R</option>');
                $('#vehicle-model').append('<option value="Honda BeAT">Honda BeAT</option>');
                $('#vehicle-model').append('<option value="Honda ADV160">Honda ADV160</option>');
                $('#vehicle-model').append('<option value="Honda RS150R">Honda RS150R</option>');
                $('#vehicle-model').append('<option value="Honda X-ADV">Honda X-ADV</option>');
                $('#vehicle-model').append('<option value="Honda EX5">Honda EX5</option>');
                $('#vehicle-model').append('<option value="Honda CB250R">Honda CB250R</option>');
                $('#vehicle-model').append('<option value="Honda Vario">Honda Vario</option>');
                $('#vehicle-model').append('<option value="Honda CBR650R">Honda CBR650R</option>');
                $('#vehicle-model').append('<option value="Honda Dash 125">Honda Dash 125</option>');
                $('#vehicle-model').append('<option value="Honda Rebel 500">Honda Rebel 500</option>');
                $('#vehicle-model').append('<option value="Honda CB500X">Honda CB500X</option>');
                $('#vehicle-model').append('<option value="Honda Wave125i">Honda Wave125i</option>');
                $('#vehicle-model').append('<option value="Honda CBR600RR">Honda CBR600RR</option>');
                $('#vehicle-model').append('<option value="Honda CB500F">Honda CB500F</option>');
                $('#vehicle-model').append('<option value="Honda Forza">Honda Forza</option>');
                $('#vehicle-model').append('<option value="Honda Wave Alpha">Honda Wave Alpha</option>');
                $('#vehicle-model').append('<option value="Honda ADV 150">Honda ADV 150</option>');
                $('#vehicle-model').append('<option value="Honda CB650R">Honda CB650R</option>');
                $('#vehicle-model').append('<option value="Honda MSX125 SF">Honda MSX125 SF</option>');
                $('#vehicle-model').append('<option value="Honda CRF250">Honda CRF250</option>');
                $('#vehicle-model').append('<option value="Honda PCX">Honda PCX</option>');
                $('#vehicle-model').append('<option value="Honda CBR500R">Honda CBR500R</option>');
                $('#vehicle-model').append('<option value="Honda CBR1000RR-R">Honda CBR1000RR-R</option>');
                $('#vehicle-model').append('<option value="Honda GL1800 Gold Wing">Honda GL1800 Gold Wing</option>');
                $('#vehicle-model').append('<option value="Honda CRF1100L Africa Twin">Honda CRF1100L Africa Twin</option>');
                $('#vehicle-model').append('<option value="Honda CBR1000RR">Honda CBR1000RR</option>');
                $('#vehicle-model').append('<option value="Honda CB1000R">Honda CB1000R</option>');
                $('#vehicle-model').append('<option value="Honda CRF1100L Africa Twin Adventure Sports">Honda CRF1100L Africa Twin Adventure Sports</option>');
                break;
            case 'Kawasaki':
                $('#vehicle-model').append('<option value="Kawasaki Ninja 250">Kawasaki Ninja 250</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z125 PRO">Kawasaki Z125 PRO</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 250 SL">Kawasaki Ninja 250 SL</option>');
                $('#vehicle-model').append('<option value="Kawasaki Vulcan S">Kawasaki Vulcan S</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z 250">Kawasaki Z 250</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z900 ABS">Kawasaki Z900 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 650 ABS">Kawasaki Ninja 650 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 400">Kawasaki Ninja 400</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z900">Kawasaki Z900</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-6R">Kawasaki Ninja ZX-6R</option>');
                $('#vehicle-model').append('<option value="Kawasaki Vulcan 900 Classic">Kawasaki Vulcan 900 Classic</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys 650">Kawasaki Versys 650</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-25RR">Kawasaki Ninja ZX-25RR</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja H2">Kawasaki Ninja H2</option>');
                $('#vehicle-model').append('<option value="Kawasaki KLX150BF">Kawasaki KLX150BF</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys 1000 SE">Kawasaki Versys 1000 SE</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja H2SX">Kawasaki Ninja H2SX</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys-X 250">Kawasaki Versys-X 250</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z650 ABS">Kawasaki Z650 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z900 SE">Kawasaki Z900 SE</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 250 ABS">Kawasaki Ninja 250 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki 1400 GTR ABS">Kawasaki 1400 GTR ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki KLX450R">Kawasaki KLX450R</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-14R ABS">Kawasaki Ninja ZX-14R ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX450F">Kawasaki KX450F</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z 1000">Kawasaki Z 1000</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX65">Kawasaki KX65</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z900RS">Kawasaki Z900RS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys 1000GT">Kawasaki Versys 1000GT</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-10 RR">Kawasaki Ninja ZX-10 RR</option>');
                $('#vehicle-model').append('<option value="Kawasaki J300 ABS">Kawasaki J300 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX250F">Kawasaki KX250F</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX85-D">Kawasaki KX85-D</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-10R">Kawasaki Ninja ZX-10R</option>');
                $('#vehicle-model').append('<option value="Kawasaki Vulcan S ABS">Kawasaki Vulcan S ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki W800">Kawasaki W800</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 1000 ABS">Kawasaki Ninja 1000 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 1000SX">Kawasaki Ninja 1000SX</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys 1000 STD">Kawasaki Versys 1000 STD</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z 400">Kawasaki Z 400</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z H2 SE">Kawasaki Z H2 SE</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX 250X">Kawasaki KX 250X</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX 250">Kawasaki KX 250</option>');
                $('#vehicle-model').append('<option value="Kawasaki KLX 140R">Kawasaki KLX 140R</option>');
                break;
            case 'Sym':
                $('#vehicle-model').append('<option value="Sym Jet14 200">Sym Jet14 200</option>');
                $('#vehicle-model').append('<option value="Sym Husky 150">Sym Husky 150</option>');
                $('#vehicle-model').append('<option value="Sym Mio 110">Sym Mio 110</option>');
                $('#vehicle-model').append('<option value="Sym Sport Rider 125i">Sym Sport Rider 125i</option>');
                $('#vehicle-model').append('<option value="Sym Tuscany">Sym Tuscany</option>');
                $('#vehicle-model').append('<option value="Sym VF3i 185 Pro">Sym VF3i 185 Pro</option>');
                $('#vehicle-model').append('<option value="Sym Maxsym">Sym Maxsym</option>');
                $('#vehicle-model').append('<option value="Sym Jet X">Sym Jet X</option>');
                break;
            case 'Harley-Davidson':
                $('#vehicle-model').append('<option value="Harley-Davidson Street Bob">Street Bob</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Low Rider">Low Rider</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Fat Boy">Fat Boy</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Sportster S">Sportster S</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Nightster">Nightster</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Road Glide">Road Glide</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Nightster Special">Nightster Special</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Road King">Road King</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Low Rider ST">Low Rider ST</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Pan America 1250">Pan America 1250</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Ultra Limited">Ultra Limited</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Fat Bob">Fat Bob</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Tri Glide Ultra">Tri Glide Ultra</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Heritage Classic">Heritage Classic</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Sport Glide">Sport Glide</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Breakout 117">Breakout 117</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Road Glide ST">Road Glide ST</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson CVO Road Glide">CVO Road Glide</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Street Glide">Street Glide</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Freewheeler">Freewheeler</option>');
                break;
            case 'Suzuki (Motor)':
                $('#vehicle-model').append('<option value="Suzuki Raider 150 Fi">Raider 150 Fi</option>');
                $('#vehicle-model').append('<option value="Suzuki V-Strom 650">V-Strom 650</option>');
                $('#vehicle-model').append('<option value="Suzuki GSX-R150">GSX-R150</option>');
                $('#vehicle-model').append('<option value="Suzuki V-Strom 800DE">V-Strom 800DE</option>');
                $('#vehicle-model').append('<option value="Suzuki GSX-R 1000">GSX-R 1000</option>');
                $('#vehicle-model').append('<option value="Suzuki GSX-S750">GSX-S750</option>');
                $('#vehicle-model').append('<option value="Suzuki GSX-S1000">GSX-S1000</option>');
                $('#vehicle-model').append('<option value="Suzuki Burgman 400">Burgman 400</option>');
                $('#vehicle-model').append('<option value="Suzuki Hayabusa">Hayabusa</option>');
                $('#vehicle-model').append('<option value="Suzuki Gixxer 250">Gixxer 250</option>');
                break;
            case 'Benelli':
                $('#vehicle-model').append('<option value="Benelli VZ 125i">VZ 125i</option>');
                $('#vehicle-model').append('<option value="Benelli TNT 25">TNT 25</option>');
                $('#vehicle-model').append('<option value="Benelli RFS 150I">RFS 150I</option>');
                $('#vehicle-model').append('<option value="Benelli TRK 502">TRK 502</option>');
                $('#vehicle-model').append('<option value="Benelli TNT 135">TNT 135</option>');
                break;
            case 'Ducati':
                $('#vehicle-model').append('<option value="Ducati Streetfighter V2">Streetfighter V2</option>');
                $('#vehicle-model').append('<option value="Ducati Panigale V4">Panigale V4</option>');
                $('#vehicle-model').append('<option value="Ducati Monster 821">Monster 821</option>');
                $('#vehicle-model').append('<option value="Ducati Scrambler Icon">Scrambler Icon</option>');
                $('#vehicle-model').append('<option value="Ducati Hypermotard 950">Hypermotard 950</option>');
                $('#vehicle-model').append('<option value="Ducati Panigale V2">Panigale V2</option>');
                $('#vehicle-model').append('<option value="Ducati Scrambler Nightshift">Scrambler Nightshift</option>');
                $('#vehicle-model').append('<option value="Ducati Multistrada V4">Multistrada V4</option>');
                $('#vehicle-model').append('<option value="Ducati Desert X">Desert X</option>');
                $('#vehicle-model').append('<option value="Ducati Monster SP">Monster SP</option>');
                $('#vehicle-model').append('<option value="Ducati Multistrada V2">Multistrada V2</option>');
                $('#vehicle-model').append('<option value="Ducati Panigale V4 SP2">Panigale V4 SP2</option>');
                $('#vehicle-model').append('<option value="Ducati Panigale V4R">Panigale V4R</option>');
                break;
            case 'BMW (Motor)':
                $('#vehicle-model').append('<option value="BMW CE 04">CE 04</option>');
                $('#vehicle-model').append('<option value="BMW G 310 GS">G 310 GS</option>');
                $('#vehicle-model').append('<option value="BMW S 1000 XR">S 1000 XR</option>');
                $('#vehicle-model').append('<option value="BMW C 400 GT">C 400 GT</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 GS">R 1250 GS</option>');
                $('#vehicle-model').append('<option value="BMW K 1600 GTL">K 1600 GTL</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 GS Adventure">R 1250 GS Adventure</option>');
                $('#vehicle-model').append('<option value="BMW G 310 R">G 310 R</option>');
                $('#vehicle-model').append('<option value="BMW S 1000 R">S 1000 R</option>');
                $('#vehicle-model').append('<option value="BMW C 400 X">C 400 X</option>');
                $('#vehicle-model').append('<option value="BMW K 1600 GT">K 1600 GT</option>');
                $('#vehicle-model').append('<option value="BMW S 1000 RR">S 1000 RR</option>');
                $('#vehicle-model').append('<option value="BMW K 1600 B">K 1600 B</option>');
                $('#vehicle-model').append('<option value="BMW R Nine T">R Nine T</option>');
                $('#vehicle-model').append('<option value="BMW F 900 XR">F 900 XR</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 RT">R 1250 RT</option>');
                $('#vehicle-model').append('<option value="BMW R Nine T Scrambler">R Nine T Scrambler</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 RS">R 1250 RS</option>');
                $('#vehicle-model').append('<option value="BMW F 900 R">F 900 R</option>');
                $('#vehicle-model').append('<option value="BMW R Nine T Urban G/S">R Nine T Urban G/S</option>');
                $('#vehicle-model').append('<option value="BMW R Nine T Pure">R Nine T Pure</option>');
                $('#vehicle-model').append('<option value="BMW R18 First Edition">R18 First Edition</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 R">R 1250 R</option>');
                $('#vehicle-model').append('<option value="BMW M 1000 R">M 1000 R</option>');
                $('#vehicle-model').append('<option value="BMW R18 Transcontinental">R18 Transcontinental</option>');
                $('#vehicle-model').append('<option value="BMW R18 Classic">R18 Classic</option>');
                $('#vehicle-model').append('<option value="BMW M 1000 RR">M 1000 RR</option>');
                $('#vehicle-model').append('<option value="BMW R18 Bagger">R18 Bagger</option>');
                break;
            case 'Vespa':
                $('#vehicle-model').append('<option value="Vespa Sprint 150">Sprint 150</option>');
                $('#vehicle-model').append('<option value="Vespa S 125">S 125</option>');
                $('#vehicle-model').append('<option value="Vespa Primavera 150">Primavera 150</option>');
                $('#vehicle-model').append('<option value="Vespa GTS Super">GTS Super</option>');
                break;
            case 'Aprilia':
                $('#vehicle-model').append('<option value="Aprilia SR GT 200">SR GT 200</option>');
                $('#vehicle-model').append('<option value="Aprilia RS 660">RS 660</option>');
                $('#vehicle-model').append('<option value="Aprilia RSV4 1100 Factory">RSV4 1100 Factory</option>');
                $('#vehicle-model').append('<option value="Aprilia Tuono V4">Tuono V4</option>');
                $('#vehicle-model').append('<option value="Aprilia Tuono 660">Tuono 660</option>');
                $('#vehicle-model').append('<option value="Aprilia Tuareg 660">Tuareg 660</option>');
                $('#vehicle-model').append('<option value="Aprilia RS 660 Extrema">RS 660 Extrema</option>');
                break;
            case 'Daiichi':
                $('#vehicle-model').append('<option value="Daiichi Sirius 110 Z">Sirius 110 Z</option>');
                $('#vehicle-model').append('<option value="Daiichi Megelli 250 SR">Megelli 250 SR</option>');
                $('#vehicle-model').append('<option value="Daiichi Megelli 250 MR">Megelli 250 MR</option>');
                $('#vehicle-model').append('<option value="Daiichi Megelli 250 RR">Megelli 250 RR</option>');
                $('#vehicle-model').append('<option value="Daiichi Cfmoto 650 TR">Cfmoto 650 TR</option>');
                $('#vehicle-model').append('<option value="Daiichi Caro Pro 110">Caro Pro 110</option>');
                $('#vehicle-model').append('<option value="Daiichi Cfmoto 650 NK">Cfmoto 650 NK</option>');
                $('#vehicle-model').append('<option value="Daiichi Caro 70 AX">Caro 70 AX</option>');
                break;
            case 'Modenas':
                $('#vehicle-model').append('<option value="Modenas Elegan 250">Elegan 250</option>');
                $('#vehicle-model').append('<option value="Modenas Kriss 110">Kriss 110</option>');
                $('#vehicle-model').append('<option value="Modenas Pulsar RS200">Pulsar RS200</option>');
                $('#vehicle-model').append('<option value="Modenas Karisma 125S">Karisma 125S</option>');
                $('#vehicle-model').append('<option value="Modenas CT 115S">CT 115S</option>');
                $('#vehicle-model').append('<option value="Modenas Kriss MR2">Kriss MR2</option>');
                $('#vehicle-model').append('<option value="Modenas Dominar D400">Dominar D400</option>');
                $('#vehicle-model').append('<option value="Modenas Pulsar NS200">Pulsar NS200</option>');
                $('#vehicle-model').append('<option value="Modenas V15">V15</option>');
                $('#vehicle-model').append('<option value="Modenas Pulsar NS160">Pulsar NS160</option>');
                break;
            case 'Piaggio':
                $('#vehicle-model').append('<option value="Piaggio Medley S 150">Medley S 150</option>');
                break;
            case 'Moto Guzzi':
                $('#vehicle-model').append('<option value="Moto Guzzi V85 TT">V85 TT</option>');
                $('#vehicle-model').append('<option value="Moto Guzzi V100">V100</option>');
                $('#vehicle-model').append('<option value="Moto Guzzi V7">V7</option>');
                break;
            case 'GPX':
                $('#vehicle-model').append('<option value="GPX Demon GR200R">Demon GR200R</option>');
                $('#vehicle-model').append('<option value="GPX Legend 150S">Legend 150S</option>');
                $('#vehicle-model').append('<option value="GPX Legend 250 Twin">Legend 250 Twin</option>');
                $('#vehicle-model').append('<option value="GPX POPZ 110">POPZ 110</option>');
                $('#vehicle-model').append('<option value="GPX Demon 150GN">Demon 150GN</option>');
                break;
            case 'Royal Enfield':
                $('#vehicle-model').append('<option value="Royal Enfield Classic 350">Classic 350</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Meteor 350">Meteor 350</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Hunter 350">Hunter 350</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Interceptor 650">Interceptor 650</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Continental GT 650">Continental GT 650</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Himalayan">Himalayan</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Super Meteor 650">Super Meteor 650</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Scram 411">Scram 411</option>');
                break;
            case 'Brixton':
                $('#vehicle-model').append('<option value="Brixton BX 150 R">BX 150 R</option>');
                $('#vehicle-model').append('<option value="Brixton BX 150 X">BX 150 X</option>');
                $('#vehicle-model').append('<option value="Brixton BX 150">BX 150</option>');
                $('#vehicle-model').append('<option value="Brixton Cromwell 1200">Cromwell 1200</option>');
                break;

                //van

            case 'Toyota (Van)':
                $('#vehicle-model').append('<option value="Toyota Hiace">Toyota Hiace </option>');
                $('#vehicle-model').append('<option value="Toyota Hiace SLWB">Toyota Hiace SLWB </option>');
                break;
            case 'Nissan (Van)':
                $('#vehicle-model').append('<option value="Toyota Hiace">Toyota Hiace </option>');
                $('#vehicle-model').append('<option value="Toyota Hiace SLWB">Toyota Hiace SLWB </option>');
                break;
            case 'Daihatsu':
                $('#vehicle-model').append('<option value="Daihatsu Gran Max ">Gran Max</option>');
                break;
            case 'Foton (Van)':
                $('#vehicle-model').append('<option value="Foton View CS2">View CS2</option>');
                $('#vehicle-model').append('<option value="Foton View C2">View C2</option>');
                $('#vehicle-model').append('<option value="Foton Daimler EST A">EST A (Lorry)</option>');
                $('#vehicle-model').append('<option value="Foton Daimler EST">EST</option>');
                $('#vehicle-model').append('<option value="Foton Toplander">Toplander (Lorry)</option>');
                break;

                //lorry
            case 'Foton (Lorry)':
                $('#vehicle-model').append('<option value="Foton Daimler EST A">EST A </option>');
                $('#vehicle-model').append('<option value="Foton Daimler EST">EST</option>');
                $('#vehicle-model').append('<option value="Foton Toplander">Toplander </option>');
                break;
            case 'Fuso':
                $('#vehicle-model').append('<option value="Fuso FN62FM">FN62FM</option>');
                $('#vehicle-model').append('<option value="Fuso FM65FN">FM65FN</option>');
                $('#vehicle-model').append('<option value="Fuso FJ1828R">FJ1828R</option>');
                $('#vehicle-model').append('<option value="Fuso FM65FJ">FM65FJ</option>');
                $('#vehicle-model').append('<option value="Fuso FG83PE">FG83PE</option>');
                $('#vehicle-model').append('<option value="Fuso FE71PB">FE71PB</option>');
                $('#vehicle-model').append('<option value="Fuso FE85PG">FE85PG</option>');
                $('#vehicle-model').append('<option value="Fuso FE85PE">FE85PE</option>');
                break;
            case 'Volvo (Lorry)':
                $('#vehicle-model').append('<option value="Volvo FM">Volvo FM </option>');
                $('#vehicle-model').append('<option value="Volvo FH16">Volvo FH16 </option>');
                $('#vehicle-model').append('<option value="Volvo FMX">Volvo FMX </option>');
                $('#vehicle-model').append('<option value="Volvo FH">Volvo FH </option>');
                break;
            case 'Hino':
                $('#vehicle-model').append('<option value="Hino 300 Series">300 Series</option>');
                $('#vehicle-model').append('<option value="Hino 500 Series">500 Series</option>');
                $('#vehicle-model').append('<option value="Hino 700 Series">700 Series</option>');
                break;
            case 'UD Trucks':
                $('#vehicle-model').append('<option value="UD Trucks Quester GKE">Quester GKE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester CWE">Quester CWE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Croner LKE">Croner LKE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester CDE">Quester CDE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester GWE">Quester GWE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester CKE">Quester CKE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester GDE">Quester GDE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Kuzer RKE">Kuzer RKE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester CGE">Quester CGE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Croner PKE">Croner PKE</option>');
                break;
            case 'CAMC':
                $('#vehicle-model').append('<option value="CAMC Tractor Unit">Tractor Unit</option>');
                $('#vehicle-model').append('<option value="CAMC Tipper-Dump">Tipper-Dump</option>');
                $('#vehicle-model').append('<option value="CAMC Cargo">Cargo</option>');
                $('#vehicle-model').append('<option value="CAMC Mixer Truck">Mixer Truck</option>');
                $('#vehicle-model').append('<option value="CAMC Special">Special</option>');
                break;
            case 'JMC':
                $('#vehicle-model').append('<option value="JMC Potente">Potente</option>');
                $('#vehicle-model').append('<option value="JMC N800">N800</option>');
                break;
            case 'Isuzu (Lorry)':
                $('#vehicle-model').append('<option value="Isuzu FORWARD FVR">Isuzu FORWARD FVR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NPS">Isuzu ELF NPS (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NPR">Isuzu ELF NPR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA Prime EXZ">Isuzu GIGA Prime EXZ (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NMR">Isuzu ELF NMR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NQR">Isuzu ELF NQR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA FXZ">Isuzu GIGA FXZ (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA Prime EXR">Isuzu GIGA Prime EXR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA Prime CYZ">Isuzu GIGA Prime CYZ (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA Prime GXR">Isuzu GIGA Prime GXR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu FORWARD FSR">Isuzu FORWARD FSR (Lorry)</option>');
                break;
        }
    });
});