$(document).ready(function () {
    $('#vehicle-make').change(function () {
        var selectedMake = $(this).val();
        $('#vehicle-model').empty(); // Clear previous options

        // Populate vehicle models based on the selected make
        switch (selectedMake) {
            case 'Alfa Romeo':
                $('#vehicle-model').append('<option value="Alfa Romeo Giulietta">Alfa Romeo Giulietta</option>');
                $('#vehicle-model').append('<option value="Alfa Romeo 159">Alfa Romeo 159</option>');
                break;
            case 'Audi':
                $('#vehicle-model').append('<option value="Audi A3 Sedan">Audi A3 Sedan</option>');
                $('#vehicle-model').append('<option value="Audi RS4 Avant">Audi RS4 Avant</option>');
                $('#vehicle-model').append('<option value="Audi A5 Sportback">Audi A5 Sportback</option>');
                $('#vehicle-model').append('<option value="Audi RS5 Sportback">Audi RS5 Sportback</option>');
                $('#vehicle-model').append('<option value="Audi RS6 Avant">Audi RS6 Avant</option>');
                $('#vehicle-model').append('<option value="Audi A7 Sportback">Audi A7 Sportback</option>');
                $('#vehicle-model').append('<option value="Audi RS7 Sportback">Audi RS7 Sportback</option>');
                $('#vehicle-model').append('<option value="Audi A8">Audi A8</option>');
                $('#vehicle-model').append('<option value="Audi Q2">Audi Q2</option>');
                $('#vehicle-model').append('<option value="Audi Q3">Audi Q3</option>');
                $('#vehicle-model').append('<option value="Audi Q3 Sportback">Audi Q3 Sportback</option>');
                $('#vehicle-model').append('<option value="Audi Q5">Audi Q5</option>');
                $('#vehicle-model').append('<option value="Audi Q5 Sportback">Audi Q5 Sportback</option>');
                $('#vehicle-model').append('<option value="Audi Q8">Audi Q8</option>');
                $('#vehicle-model').append('<option value="Audi Q8 e-tron">Audi Q8 e-tron</option>');
                $('#vehicle-model').append('<option value="Audi e-tron GT">Audi e-tron GT</option>');
                $('#vehicle-model').append('<option value="Audi Q8 e-tron Sportback">Audi Q8 e-tron Sportback</option>');
                $('#vehicle-model').append('<option value="Audi SQ8 e-tron">Audi SQ8 e-tron</option>');
                $('#vehicle-model').append('<option value="Audi SQ8 Sportback e-tron">Audi SQ8 Sportback e-tron</option>');
                $('#vehicle-model').append('<option value="Audi RSQ8">Audi RSQ8</option>');
                break;
            case 'BMW':
                $('#vehicle-model').append('<option value="BMW M135i">BMW M135i</option>');
                $('#vehicle-model').append('<option value="BMW M2 Coupe">BMW M2 Coupe</option>');
                $('#vehicle-model').append('<option value="BMW 2 Series Gran Coupe">BMW 2 Series Gran Coupe</option>');
                $('#vehicle-model').append('<option value="BMW 3 Series">BMW 3 Series</option>');
                $('#vehicle-model').append('<option value="BMW 3 Series M">BMW 3 Series M</option>');
                $('#vehicle-model').append('<option value="BMW M3">BMW M3</option>');
                $('#vehicle-model').append('<option value="BMW 4 Series Coupe">BMW 4 Series Coupe</option>');
                $('#vehicle-model').append('<option value="BMW M4 Coupe">BMW M4 Coupe</option>');
                $('#vehicle-model').append('<option value="BMW i4">BMW i4</option>');
                $('#vehicle-model').append('<option value="BMW i4 M50">BMW i4 M50</option>');
                $('#vehicle-model').append('<option value="BMW 5 Series">BMW 5 Series</option>');
                $('#vehicle-model').append('<option value="BMW i5">BMW i5</option>');
                $('#vehicle-model').append('<option value="BMW M5">BMW M5</option>');
                $('#vehicle-model').append('<option value="BMW 6 Series GT">BMW 6 Series GT</option>');
                $('#vehicle-model').append('<option value="BMW 7 Series">BMW 7 Series</option>');
                $('#vehicle-model').append('<option value="BMW i7">BMW i7</option>');
                $('#vehicle-model').append('<option value="BMW 8 Series M Coupe">BMW 8 Series M Coupe</option>');
                $('#vehicle-model').append('<option value="BMW 8 Series Gran Coupe">BMW 8 Series Gran Coupe</option>');
                $('#vehicle-model').append('<option value="BMW X1">BMW X1</option>');
                $('#vehicle-model').append('<option value="BMW iX1">BMW iX1</option>');
                $('#vehicle-model').append('<option value="BMW iX3">BMW iX3</option>');
                $('#vehicle-model').append('<option value="BMW X3">BMW X3</option>');
                $('#vehicle-model').append('<option value="BMW X4">BMW X4</option>');
                $('#vehicle-model').append('<option value="BMW iX">BMW iX</option>');
                $('#vehicle-model').append('<option value="BMW X5">BMW X5</option>');
                $('#vehicle-model').append('<option value="BMW X6">BMW X6</option>');
                $('#vehicle-model').append('<option value="BMW X7">BMW X7</option>');
                $('#vehicle-model').append('<option value="BMW Z4">BMW Z4</option>');
                $('#vehicle-model').append('<option value="BMW iX M60">BMW iX M60</option>');
                break;
            case 'Borgward':
                $('#vehicle-model').append('<option value="Borgward BX5">Borgward BX5</option>');
                break;
            case 'Chery':
                $('#vehicle-model').append('<option value="Chery Omoda 5">Chery Omoda 5</option>');
                $('#vehicle-model').append('<option value="Chery Tiggo 8 Pro">Chery Tiggo 8 Pro</option>');
                $('#vehicle-model').append('<option value="Chery Omoda E5">Chery Omoda E5</option>');
                break;
            case 'Chevrolet':
                $('#vehicle-model').append('<option value="Chevrolet Sonic">Chevrolet Sonic</option>');
                $('#vehicle-model').append('<option value="Chevrolet Sonic Sedan">Chevrolet Sonic Sedan</option>');
                $('#vehicle-model').append('<option value="Chevrolet Malibu">Chevrolet Malibu</option>');
                $('#vehicle-model').append('<option value="Chevrolet Cruze">Chevrolet Cruze</option>');
                $('#vehicle-model').append('<option value="Chevrolet Orlando">Chevrolet Orlando</option>');
                $('#vehicle-model').append('<option value="Chevrolet Captiva">Chevrolet Captiva</option>');
                $('#vehicle-model').append('<option value="Chevrolet Colorado">Chevrolet Colorado</option>');
                break;
            case 'Citroen':
                $('#vehicle-model').append('<option value="Citroen DS3">Citroen DS3</option>');
                $('#vehicle-model').append('<option value="Citroen DS4">Citroen DS4</option>');
                $('#vehicle-model').append('<option value="Citroen DS5">Citroen DS5</option>');
                $('#vehicle-model').append('<option value="Citroen DS7 Crossback">Citroen DS7 Crossback</option>');
                $('#vehicle-model').append('<option value="Citroen C4 Picasso">Citroen C4 Picasso</option>');
                $('#vehicle-model').append('<option value="Citroen Grand C4 Picasso">Citroen Grand C4 Picasso</option>');
                break;
            case 'Ford':
                $('#vehicle-model').append('<option value="Ford Ranger">Ford Ranger</option>');
                $('#vehicle-model').append('<option value="Ford Ranger Raptor">Ford Ranger Raptor</option>');
                $('#vehicle-model').append('<option value="Ford Mustang">Ford Mustang</option>');
                $('#vehicle-model').append('<option value="Ford Everest">Ford Everest</option>');
                $('#vehicle-model').append('<option value="Ford Fiesta">Ford Fiesta</option>');
                $('#vehicle-model').append('<option value="Ford Fiesta Sedan">Ford Fiesta Sedan</option>');
                $('#vehicle-model').append('<option value="Ford Fiesta ST">Ford Fiesta ST</option>');
                $('#vehicle-model').append('<option value="Ford Focus">Ford Focus</option>');
                $('#vehicle-model').append('<option value="Ford Focus Sedan">Ford Focus Sedan</option>');
                $('#vehicle-model').append('<option value="Ford Focus ST">Ford Focus ST</option>');
                $('#vehicle-model').append('<option value="Ford Mondeo">Ford Mondeo</option>');
                $('#vehicle-model').append('<option value="Ford S-MAX">Ford S-MAX</option>');
                $('#vehicle-model').append('<option value="Ford EcoSport">Ford EcoSport</option>');
                $('#vehicle-model').append('<option value="Ford Kuga">Ford Kuga</option>');
                break;
            case 'Honda':
                $('#vehicle-model').append('<option value="Honda WR-V">Honda WR-V</option>');
                $('#vehicle-model').append('<option value="Honda City">Honda City</option>');
                $('#vehicle-model').append('<option value="Honda City Hatchback">Honda City Hatchback</option>');
                $('#vehicle-model').append('<option value="Honda Civic">Honda Civic</option>');
                $('#vehicle-model').append('<option value="Honda Civic Type R">Honda Civic Type R</option>');
                $('#vehicle-model').append('<option value="Honda Accord">Honda Accord</option>');
                $('#vehicle-model').append('<option value="Honda HR-V">Honda HR-V</option>');
                $('#vehicle-model').append('<option value="Honda CR-V">Honda CR-V</option>');
                $('#vehicle-model').append('<option value="Honda Jazz">Honda Jazz</option>');
                $('#vehicle-model').append('<option value="Honda BR-V">Honda BR-V</option>');
                $('#vehicle-model').append('<option value="Honda Stream">Honda Stream</option>');
                $('#vehicle-model').append('<option value="Honda Odyssey">Honda Odyssey</option>');
                $('#vehicle-model').append('<option value="Honda CR-Z">Honda CR-Z</option>');
                break;
            case 'Hyundai':
                $('#vehicle-model').append('<option value="Hyundai Creta">Hyundai Creta</option>');
                $('#vehicle-model').append('<option value="Hyundai Kona">Hyundai Kona</option>');
                $('#vehicle-model').append('<option value="Hyundai Kona Electric">Hyundai Kona Electric</option>');
                $('#vehicle-model').append('<option value="Hyundai Tucson">Hyundai Tucson</option>');
                $('#vehicle-model').append('<option value="Hyundai Ioniq 5">Hyundai Ioniq 5</option>');
                $('#vehicle-model').append('<option value="Hyundai Ioniq 6">Hyundai Ioniq 6</option>');
                $('#vehicle-model').append('<option value="Hyundai Palisade">Hyundai Palisade</option>');
                $('#vehicle-model').append('<option value="Hyundai Staria">Hyundai Staria</option>');
                $('#vehicle-model').append('<option value="Hyundai i10">Hyundai i10</option>');
                $('#vehicle-model').append('<option value="Hyundai Elantra">Hyundai Elantra</option>');
                $('#vehicle-model').append('<option value="Hyundai Ioniq">Hyundai Ioniq</option>');
                $('#vehicle-model').append('<option value="Hyundai i30">Hyundai i30</option>');
                $('#vehicle-model').append('<option value="Hyundai i30 N">Hyundai i30 N</option>');
                $('#vehicle-model').append('<option value="Hyundai Veloster">Hyundai Veloster</option>');
                $('#vehicle-model').append('<option value="Hyundai Sonata">Hyundai Sonata</option>');
                $('#vehicle-model').append('<option value="Hyundai i40 Sedan">Hyundai i40 Sedan</option>');
                $('#vehicle-model').append('<option value="Hyundai i40 Tourer">Hyundai i40 Tourer</option>');
                $('#vehicle-model').append('<option value="Hyundai Santa Fe">Hyundai Santa Fe</option>');
                $('#vehicle-model').append('<option value="Hyundai Grand Starex">Hyundai Grand Starex</option>');
                $('#vehicle-model').append('<option value="Hyundai Genesis">Hyundai Genesis</option>');
                break;
            case 'Infiniti':
                $('#vehicle-model').append('<option value="Infiniti Q50">Infiniti Q50</option>');
                $('#vehicle-model').append('<option value="Infiniti Q60">Infiniti Q60</option>');
                $('#vehicle-model').append('<option value="Infiniti Q70">Infiniti Q70</option>');
                $('#vehicle-model').append('<option value="Infiniti QX50">Infiniti QX50</option>');
                $('#vehicle-model').append('<option value="Infiniti QX70">Infiniti QX70</option>');
                $('#vehicle-model').append('<option value="Infiniti QX80">Infiniti QX80</option>');
                break;
            case 'Isuzu':
                $('#vehicle-model').append('<option value="Isuzu D-MAX">Isuzu D-MAX</option>');
                $('#vehicle-model').append('<option value="Isuzu MU-X">Isuzu MU-X</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NLR">Isuzu ELF NLR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu FORWARD FVR">Isuzu FORWARD FVR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NPS">Isuzu ELF NPS (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NPR">Isuzu ELF NPR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA Prime EXZ">Isuzu GIGA Prime EXZ (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NMR">Isuzu ELF NMR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu ELF NQR">Isuzu ELF NQR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA FXZ">Isuzu GIGA FXZ (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA Prime EXR">Isuzu GIGA Prime EXR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA Prime CYZ">Isuzu GIGA Prime CYZ (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu GIGA Prime GXR">Isuzu GIGA Prime GXR (Lorry)</option>');
                $('#vehicle-model').append('<option value="Isuzu FORWARD FSR">Isuzu FORWARD FSR (Lorry)</option>');
                break;
            case 'Jaguar':
                $('#vehicle-model').append('<option value="Jaguar XE">Jaguar XE</option>');
                $('#vehicle-model').append('<option value="Jaguar XF">Jaguar XF</option>');
                $('#vehicle-model').append('<option value="Jaguar XJ">Jaguar XJ</option>');
                $('#vehicle-model').append('<option value="Jaguar F-Pace">Jaguar F-Pace</option>');
                $('#vehicle-model').append('<option value="Jaguar I-Pace">Jaguar I-Pace</option>');
                break;
            case 'Jeep':
                $('#vehicle-model').append('<option value="Jeep Compass">Jeep Compass</option>');
                $('#vehicle-model').append('<option value="Jeep Cherokee">Jeep Cherokee</option>');
                $('#vehicle-model').append('<option value="Jeep Grand Cherokee">Jeep Grand Cherokee</option>');
                $('#vehicle-model').append('<option value="Jeep Grand Cherokee SRT">Jeep Grand Cherokee SRT</option>');
                $('#vehicle-model').append('<option value="Jeep Wrangler">Jeep Wrangler</option>');
                break;
            case 'Kia':
                $('#vehicle-model').append('<option value="Kia Niro EV">Kia Niro EV</option>');
                $('#vehicle-model').append('<option value="Kia Sorento">Kia Sorento</option>');
                $('#vehicle-model').append('<option value="Kia Carnival">Kia Carnival</option>');
                $('#vehicle-model').append('<option value="Kia EV6">Kia EV6</option>');
                $('#vehicle-model').append('<option value="Kia Picanto">Kia Picanto</option>');
                $('#vehicle-model').append('<option value="Kia Rio">Kia Rio</option>');
                $('#vehicle-model').append('<option value="Kia Rio Sedan">Kia Rio Sedan</option>');
                $('#vehicle-model').append('<option value="Kia Cerato">Kia Cerato</option>');
                $('#vehicle-model').append('<option value="Kia Cerato Koup">Kia Cerato Koup</option>');
                $('#vehicle-model').append('<option value="Kia Optima">Kia Optima</option>');
                $('#vehicle-model').append('<option value="Kia Stinger">Kia Stinger</option>');
                $('#vehicle-model').append('<option value="Kia Sportage">Kia Sportage</option>');
                $('#vehicle-model').append('<option value="Kia Pregio">Kia Pregio</option>');
                $('#vehicle-model').append('<option value="Kia Seltos">Kia Seltos</option>');
                break;
            case 'Land Rover':
                $('#vehicle-model').append('<option value="Land Rover Defender">Land Rover Defender</option>');
                $('#vehicle-model').append('<option value="Land Rover Discovery Sport">Land Rover Discovery Sport</option>');
                $('#vehicle-model').append('<option value="Land Rover Discovery">Land Rover Discovery</option>');
                $('#vehicle-model').append('<option value="Land Rover Range Rover Evoque">Land Rover Range Rover Evoque</option>');
                $('#vehicle-model').append('<option value="Land Rover Range Rover Velar">Land Rover Range Rover Velar</option>');
                $('#vehicle-model').append('<option value="Land Rover Range Rover Sport">Land Rover Range Rover Sport</option>');
                $('#vehicle-model').append('<option value="Land Rover Range Rover">Land Rover Range Rover</option>');
                break;
            case 'Lexus':
                $('#vehicle-model').append('<option value="Lexus ES">Lexus ES</option>');
                $('#vehicle-model').append('<option value="Lexus LS">Lexus LS</option>');
                $('#vehicle-model').append('<option value="Lexus NX">Lexus NX</option>');
                $('#vehicle-model').append('<option value="Lexus RX">Lexus RX</option>');
                $('#vehicle-model').append('<option value="Lexus LX">Lexus LX</option>');
                $('#vehicle-model').append('<option value="Lexus LC">Lexus LC</option>');
                $('#vehicle-model').append('<option value="Lexus UX">Lexus UX</option>');
                $('#vehicle-model').append('<option value="Lexus LM">Lexus LM</option>');
                $('#vehicle-model').append('<option value="Lexus CT">Lexus CT</option>');
                $('#vehicle-model').append('<option value="Lexus IS">Lexus IS</option>');
                $('#vehicle-model').append('<option value="Lexus RC">Lexus RC</option>');
                $('#vehicle-model').append('<option value="Lexus RC F">Lexus RC F</option>');
                $('#vehicle-model').append('<option value="Lexus GS">Lexus GS</option>');
                $('#vehicle-model').append('<option value="Lexus GS F">Lexus GS F</option>');
                break;
            case 'Mazda':
                $('#vehicle-model').append('<option value="Mazda 2 Hatchback">Mazda 2 Hatchback</option>');
                $('#vehicle-model').append('<option value="Mazda 2 Sedan">Mazda 2 Sedan</option>');
                $('#vehicle-model').append('<option value="Mazda 3 Hatchback">Mazda 3 Hatchback</option>');
                $('#vehicle-model').append('<option value="Mazda 3 Sedan">Mazda 3 Sedan</option>');
                $('#vehicle-model').append('<option value="Mazda 6 Sedan">Mazda 6 Sedan</option>');
                $('#vehicle-model').append('<option value="Mazda 6 Grand Touring">Mazda 6 Grand Touring</option>');
                $('#vehicle-model').append('<option value="Mazda CX-3">Mazda CX-3</option>');
                $('#vehicle-model').append('<option value="Mazda CX-5">Mazda CX-5</option>');
                $('#vehicle-model').append('<option value="Mazda CX-8">Mazda CX-8</option>');
                $('#vehicle-model').append('<option value="Mazda CX-9">Mazda CX-9</option>');
                $('#vehicle-model').append('<option value="Mazda BT-50">Mazda BT-50</option>');
                $('#vehicle-model').append('<option value="Mazda MX-5">Mazda MX-5</option>');
                $('#vehicle-model').append('<option value="Mazda CX-30">Mazda CX-30</option>');
                $('#vehicle-model').append('<option value="Mazda MX-30">Mazda MX-30</option>');
                $('#vehicle-model').append('<option value="Mazda 8">Mazda 8</option>');
                break;
            case 'Mercedes-Benz':
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG A-Class">Mercedes-Benz AMG A-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz A-Class Sedan">Mercedes-Benz A-Class Sedan</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG A-Class Sedan">Mercedes-Benz AMG A-Class Sedan</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz B-Class">Mercedes-Benz B-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz CLA">Mercedes-Benz CLA</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG CLA">Mercedes-Benz AMG CLA</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz GLA">Mercedes-Benz GLA</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLA">Mercedes-Benz AMG GLA</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz EQA">Mercedes-Benz EQA</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz GLB">Mercedes-Benz GLB</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLB">Mercedes-Benz AMG GLB</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz EQB">Mercedes-Benz EQB</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz C-Class">Mercedes-Benz C-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG C-Class">Mercedes-Benz AMG C-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz C-Class Coupe">Mercedes-Benz C-Class Coupe</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG C-Class Coupe">Mercedes-Benz AMG C-Class Coupe</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz GLC">Mercedes-Benz GLC</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLC">Mercedes-Benz AMG GLC</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz GLC Coupe">Mercedes-Benz GLC Coupe</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLC Coupe">Mercedes-Benz AMG GLC Coupe</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz EQC">Mercedes-Benz EQC</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz E-Class">Mercedes-Benz E-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG E-Class">Mercedes-Benz AMG E-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz E-Class Coupe">Mercedes-Benz E-Class Coupe</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz CLS">Mercedes-Benz CLS</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG CLS">Mercedes-Benz AMG CLS</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz GLE Coupe">Mercedes-Benz GLE Coupe</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz GLE">Mercedes-Benz GLE</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG GLE Coupe">Mercedes-Benz AMG GLE Coupe</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz S-Class">Mercedes-Benz S-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz Maybach S-Class">Mercedes-Benz Maybach S-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz EQS">Mercedes-Benz EQS</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG S-Class Coupe">Mercedes-Benz AMG S-Class Coupe</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz S-Class Cabriolet">Mercedes-Benz S-Class Cabriolet</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz GLS">Mercedes-Benz GLS</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz Maybach GLS">Mercedes-Benz Maybach GLS</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG G-Class">Mercedes-Benz AMG G-Class</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz Vito Tourer">Mercedes-Benz Vito Tourer</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz SLC">Mercedes-Benz SLC</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG GT">Mercedes-Benz AMG GT</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG GT 4-Door">Mercedes-Benz AMG GT 4-Door</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz EQE">Mercedes-Benz EQE</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG EQS">Mercedes-Benz AMG EQS</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG EQE">Mercedes-Benz AMG EQE</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz AMG SL">Mercedes-Benz AMG SL</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz EQS SUV">Mercedes-Benz EQS SUV</option>');
                $('#vehicle-model').append('<option value="Mercedes-Benz EQE SUV">Mercedes-Benz EQE SUV</option>');
                break;
            case 'MINI':
                $('#vehicle-model').append('<option value="MINI 3 Door">MINI 3 Door</option>');
                $('#vehicle-model').append('<option value="MINI 5 Door">MINI 5 Door</option>');
                $('#vehicle-model').append('<option value="MINI Clubman">MINI Clubman</option>');
                $('#vehicle-model').append('<option value="MINI Countryman">MINI Countryman</option>');
                $('#vehicle-model').append('<option value="MINI Electric">MINI Electric</option>');
                $('#vehicle-model').append('<option value="MINI Convertible">MINI Convertible</option>');
                $('#vehicle-model').append('<option value="MINI Coupe">MINI Coupe</option>');
                break;
            case 'Mitsubishi':
                $('#vehicle-model').append('<option value="Mitsubishi Triton">Mitsubishi Triton</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Xpander">Mitsubishi Xpander</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Mirage">Mitsubishi Mirage</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Attrage">Mitsubishi Attrage</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Lancer">Mitsubishi Lancer</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Lancer Sportback">Mitsubishi Lancer Sportback</option>');
                $('#vehicle-model').append('<option value="Mitsubishi ASX">Mitsubishi ASX</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Outlander">Mitsubishi Outlander</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Pajero">Mitsubishi Pajero</option>');
                $('#vehicle-model').append('<option value="Mitsubishi Pajero Sport">Mitsubishi Pajero Sport</option>');
                break;
            case 'Nissan':
                $('#vehicle-model').append('<option value="Nissan Almera">Nissan Almera</option>');
                $('#vehicle-model').append('<option value="Nissan Leaf">Nissan Leaf</option>');
                $('#vehicle-model').append('<option value="Nissan Serena S-Hybrid">Nissan Serena S-Hybrid</option>');
                $('#vehicle-model').append('<option value="Nissan X-Trail">Nissan X-Trail</option>');
                $('#vehicle-model').append('<option value="Nissan Navara">Nissan Navara</option>');
                $('#vehicle-model').append('<option value="Nissan NV200">Nissan NV200</option>');
                $('#vehicle-model').append('<option value="Nissan Latio Sedan">Nissan Latio Sedan</option>');
                $('#vehicle-model').append('<option value="Nissan Latio Hatchback">Nissan Latio Hatchback</option>');
                $('#vehicle-model').append('<option value="Nissan Sylphy">Nissan Sylphy</option>');
                $('#vehicle-model').append('<option value="Nissan Teana">Nissan Teana</option>');
                $('#vehicle-model').append('<option value="Nissan X-Gear">Nissan X-Gear</option>');
                $('#vehicle-model').append('<option value="Nissan Grand Livina">Nissan Grand Livina</option>');
                $('#vehicle-model').append('<option value="Nissan Murano">Nissan Murano</option>');
                $('#vehicle-model').append('<option value="Nissan Elgrand">Nissan Elgrand</option>');
                $('#vehicle-model').append('<option value="Nissan 370Z Coupe">Nissan 370Z Coupe</option>');
                $('#vehicle-model').append('<option value="Nissan 370Z Roadster">Nissan 370Z Roadster</option>');
                $('#vehicle-model').append('<option value="Nissan NV350 Urvan">Nissan NV350 Urvan</option>');
                $('#vehicle-model').append('<option value="Nissan NV200">Nissan NV200 (Van)</option>');
                break;
            case 'Perodua':
                $('#vehicle-model').append('<option value="Perodua Axia">Perodua Axia</option>');
                $('#vehicle-model').append('<option value="Perodua Bezza">Perodua Bezza</option>');
                $('#vehicle-model').append('<option value="Perodua Myvi">Perodua Myvi</option>');
                $('#vehicle-model').append('<option value="Perodua Alza">Perodua Alza</option>');
                $('#vehicle-model').append('<option value="Perodua Aruz">Perodua Aruz</option>');
                $('#vehicle-model').append('<option value="Perodua Ativa">Perodua Ativa</option>');
                $('#vehicle-model').append('<option value="Perodua Viva">Perodua Viva</option>');
                $('#vehicle-model').append('<option value="Perodua Kenari">Perodua Kenari</option>');
                break;
            case 'Peugeot':
                $('#vehicle-model').append('<option value="Peugeot 2008">Peugeot 2008</option>');
                $('#vehicle-model').append('<option value="Peugeot 3008">Peugeot 3008</option>');
                $('#vehicle-model').append('<option value="Peugeot 5008">Peugeot 5008</option>');
                $('#vehicle-model').append('<option value="Peugeot Landtrek">Peugeot Landtrek</option>');
                $('#vehicle-model').append('<option value="Peugeot 208">Peugeot 208</option>');
                $('#vehicle-model').append('<option value="Peugeot 208 GTi">Peugeot 208 GTi</option>');
                $('#vehicle-model').append('<option value="Peugeot 308">Peugeot 308</option>');
                $('#vehicle-model').append('<option value="Peugeot 408">Peugeot 408</option>');
                $('#vehicle-model').append('<option value="Peugeot 508">Peugeot 508</option>');
                $('#vehicle-model').append('<option value="Peugeot 508 SW">Peugeot 508 SW</option>');
                $('#vehicle-model').append('<option value="Peugeot RCZ">Peugeot RCZ</option>');
                break;
            case 'Proton':
                $('#vehicle-model').append('<option value="Proton Saga">Proton Saga</option>');
                $('#vehicle-model').append('<option value="Proton Iriz">Proton Iriz</option>');
                $('#vehicle-model').append('<option value="Proton Persona">Proton Persona</option>');
                $('#vehicle-model').append('<option value="Proton S70">Proton S70</option>');
                $('#vehicle-model').append('<option value="Proton Exora">Proton Exora</option>');
                $('#vehicle-model').append('<option value="Proton X50">Proton X50</option>');
                $('#vehicle-model').append('<option value="Proton X70">Proton X70</option>');
                $('#vehicle-model').append('<option value="Proton X90">Proton X90</option>');
                $('#vehicle-model').append('<option value="Proton Satria Neo">Proton Satria Neo</option>');
                $('#vehicle-model').append('<option value="Proton Preve">Proton Preve</option>');
                $('#vehicle-model').append('<option value="Proton Suprima S">Proton Suprima S</option>');
                $('#vehicle-model').append('<option value="Proton Inspira">Proton Inspira</option>');
                $('#vehicle-model').append('<option value="Proton Perdana">Proton Perdana</option>');
                $('#vehicle-model').append('<option value="Proton Ertiga">Proton Ertiga</option>');
                break;
            case 'Subaru':
                $('#vehicle-model').append('<option value="Subaru WRX">Subaru WRX</option>');
                $('#vehicle-model').append('<option value="Subaru Outback">Subaru Outback</option>');
                $('#vehicle-model').append('<option value="Subaru XV">Subaru XV</option>');
                $('#vehicle-model').append('<option value="Subaru Forester">Subaru Forester</option>');
                $('#vehicle-model').append('<option value="Subaru BRZ">Subaru BRZ</option>');
                $('#vehicle-model').append('<option value="Subaru Legacy Sedan">Subaru Legacy Sedan</option>');
                $('#vehicle-model').append('<option value="Subaru Legacy Wagon">Subaru Legacy Wagon</option>');
                break;
            case 'Suzuki':
                $('#vehicle-model').append('<option value="Suzuki Swift Sport">Suzuki Swift Sport</option>');
                $('#vehicle-model').append('<option value="Suzuki Jimny">Suzuki Jimny</option>');
                $('#vehicle-model').append('<option value="Suzuki Alto">Suzuki Alto</option>');
                $('#vehicle-model').append('<option value="Suzuki Swift">Suzuki Swift</option>');
                $('#vehicle-model').append('<option value="Suzuki SX4">Suzuki SX4</option>');
                $('#vehicle-model').append('<option value="Suzuki S-Cross">Suzuki S-Cross</option>');
                $('#vehicle-model').append('<option value="Suzuki Kizashi">Suzuki Kizashi</option>');
                $('#vehicle-model').append('<option value="Suzuki Grand Vitara">Suzuki Grand Vitara</option>');
                break;
            case 'Toyota':
                $('#vehicle-model').append('<option value="Toyota Yaris">Toyota Yaris</option>');
                $('#vehicle-model').append('<option value="Toyota Vios">Toyota Vios</option>');
                $('#vehicle-model').append('<option value="Toyota Corolla">Toyota Corolla</option>');
                $('#vehicle-model').append('<option value="Toyota Camry">Toyota Camry</option>');
                $('#vehicle-model').append('<option value="Toyota Veloz">Toyota Veloz</option>');
                $('#vehicle-model').append('<option value="Toyota Innova">Toyota Innova</option>');
                $('#vehicle-model').append('<option value="Toyota Innova Zenix">Toyota Innova Zenix</option>');
                $('#vehicle-model').append('<option value="Toyota Alphard">Toyota Alphard</option>');
                $('#vehicle-model').append('<option value="Toyota Vellfire">Toyota Vellfire</option>');
                $('#vehicle-model').append('<option value="Toyota Corolla Cross">Toyota Corolla Cross</option>');
                $('#vehicle-model').append('<option value="Toyota Fortuner">Toyota Fortuner</option>');
                $('#vehicle-model').append('<option value="Toyota Harrier">Toyota Harrier</option>');
                $('#vehicle-model').append('<option value="Toyota Hilux">Toyota Hilux</option>');
                $('#vehicle-model').append('<option value="Toyota GR Supra">Toyota GR Supra</option>');
                $('#vehicle-model').append('<option value="Toyota Hiace">Toyota Hiace</option>');
                $('#vehicle-model').append('<option value="Toyota GR86">Toyota GR86</option>');
                $('#vehicle-model').append('<option value="Toyota GR Corolla">Toyota GR Corolla</option>');
                $('#vehicle-model').append('<option value="Toyota GR Yaris">Toyota GR Yaris</option>');
                $('#vehicle-model').append('<option value="Toyota Avanza">Toyota Avanza</option>');
                $('#vehicle-model').append('<option value="Toyota Sienta">Toyota Sienta</option>');
                $('#vehicle-model').append('<option value="Toyota Previa">Toyota Previa</option>');
                $('#vehicle-model').append('<option value="Toyota Rush">Toyota Rush</option>');
                $('#vehicle-model').append('<option value="Toyota C-HR">Toyota C-HR</option>');
                $('#vehicle-model').append('<option value="Toyota RAV4">Toyota RAV4</option>');
                $('#vehicle-model').append('<option value="Toyota 86">Toyota 86</option>');
                $('#vehicle-model').append('<option value="Toyota Prius">Toyota Prius</option>');
                $('#vehicle-model').append('<option value="Toyota Prius c">Toyota Prius c</option>');
                $('#vehicle-model').append('<option value="Toyota Hiace">Toyota Hiace (Van)</option>');
                $('#vehicle-model').append('<option value="Toyota Hiace SLWB">Toyota Hiace SLWB (Van)</option>');
                break;
            case 'Volkswagen':
                $('#vehicle-model').append('<option value="Volkswagen Golf GTI">Volkswagen Golf GTI</option>');
                $('#vehicle-model').append('<option value="Volkswagen Golf R">Volkswagen Golf R</option>');
                $('#vehicle-model').append('<option value="Volkswagen Arteon">Volkswagen Arteon</option>');
                $('#vehicle-model').append('<option value="Volkswagen Tiguan Allspace">Volkswagen Tiguan Allspace</option>');
                $('#vehicle-model').append('<option value="Volkswagen Touareg">Volkswagen Touareg</option>');
                $('#vehicle-model').append('<option value="Volkswagen Vento">Volkswagen Vento</option>');
                $('#vehicle-model').append('<option value="Volkswagen Polo">Volkswagen Polo</option>');
                $('#vehicle-model').append('<option value="Volkswagen Polo GTI">Volkswagen Polo GTI</option>');
                $('#vehicle-model').append('<option value="Volkswagen Jetta">Volkswagen Jetta</option>');
                $('#vehicle-model').append('<option value="Volkswagen Golf">Volkswagen Golf</option>');
                $('#vehicle-model').append('<option value="Volkswagen Beetle">Volkswagen Beetle</option>');
                $('#vehicle-model').append('<option value="Volkswagen Scirocco">Volkswagen Scirocco</option>');
                $('#vehicle-model').append('<option value="Volkswagen Scirocco R">Volkswagen Scirocco R</option>');
                $('#vehicle-model').append('<option value="Volkswagen Eos">Volkswagen Eos</option>');
                $('#vehicle-model').append('<option value="Volkswagen Passat">Volkswagen Passat</option>');
                $('#vehicle-model').append('<option value="Volkswagen CC">Volkswagen CC</option>');
                $('#vehicle-model').append('<option value="Volkswagen Passat CC R-Line">Volkswagen Passat CC R-Line</option>');
                $('#vehicle-model').append('<option value="Volkswagen Tiguan">Volkswagen Tiguan</option>');
                $('#vehicle-model').append('<option value="Volkswagen Cross Touran">Volkswagen Cross Touran</option>');
                $('#vehicle-model').append('<option value="Volkswagen Sharan">Volkswagen Sharan</option>');
                break;
            case 'Volvo':
                $('#vehicle-model').append('<option value="Volvo XC40">Volvo XC40</option>');
                $('#vehicle-model').append('<option value="Volvo XC40 Recharge Electric">Volvo XC40 Recharge Electric</option>');
                $('#vehicle-model').append('<option value="Volvo S60">Volvo S60</option>');
                $('#vehicle-model').append('<option value="Volvo V60">Volvo V60</option>');
                $('#vehicle-model').append('<option value="Volvo XC60">Volvo XC60</option>');
                $('#vehicle-model').append('<option value="Volvo S90">Volvo S90</option>');
                $('#vehicle-model').append('<option value="Volvo XC90">Volvo XC90</option>');
                $('#vehicle-model').append('<option value="Volvo C40">Volvo C40</option>');
                $('#vehicle-model').append('<option value="Volvo V40">Volvo V40</option>');
                $('#vehicle-model').append('<option value="Volvo S80">Volvo S80</option>');
                $('#vehicle-model').append('<option value="Volvo V90">Volvo V90</option>');
                $('#vehicle-model').append('<option value="Volvo FM">Volvo FM (Lorry)</option>');
                $('#vehicle-model').append('<option value="Volvo FH16">Volvo FH16 (Lorry)</option>');
                $('#vehicle-model').append('<option value="Volvo FMX">Volvo FMX (Lorry)</option>');
                $('#vehicle-model').append('<option value="Volvo FH">Volvo FH (Lorry)</option>');
                break;

                //motorcycle 
            case 'Yamaha':
                $('#vehicle-model').append('<option value="Yamaha NVX">Yamaha NVX</option>');
                $('#vehicle-model').append('<option value="Yamaha NMAX">Yamaha NMAX</option>');
                $('#vehicle-model').append('<option value="Yamaha Y15ZR">Yamaha Y15ZR</option>');
                $('#vehicle-model').append('<option value="Yamaha Y16ZR">Yamaha Y16ZR</option>');
                $('#vehicle-model').append('<option value="Yamaha Ego Avantiz">Yamaha Ego Avantiz</option>');
                $('#vehicle-model').append('<option value="Yamaha XMax 250">Yamaha XMax 250</option>');
                $('#vehicle-model').append('<option value="Yamaha 135LC Fi">Yamaha 135LC Fi</option>');
                $('#vehicle-model').append('<option value="Yamaha YZF-R15">Yamaha YZF-R15</option>');
                $('#vehicle-model').append('<option value="Yamaha MT-15">Yamaha MT-15</option>');
                $('#vehicle-model').append('<option value="Yamaha MT-25">Yamaha MT-25</option>');
                $('#vehicle-model').append('<option value="Yamaha YZF-R25">Yamaha YZF-R25</option>');
                $('#vehicle-model').append('<option value="Yamaha Ego Gear">Yamaha Ego Gear</option>');
                $('#vehicle-model').append('<option value="Yamaha Lagenda 115Z">Yamaha Lagenda 115Z</option>');
                $('#vehicle-model').append('<option value="Yamaha TMax">Yamaha TMax</option>');
                $('#vehicle-model').append('<option value="Yamaha MT-09">Yamaha MT-09</option>');
                $('#vehicle-model').append('<option value="Yamaha R15M">Yamaha R15M</option>');
                $('#vehicle-model').append('<option value="Yamaha MT-07">Yamaha MT-07</option>');
                $('#vehicle-model').append('<option value="Yamaha EZ115">Yamaha EZ115</option>');
                $('#vehicle-model').append('<option value="Yamaha Tracer 900 GT">Yamaha Tracer 900 GT</option>');
                $('#vehicle-model').append('<option value="Yamaha Y16ZR Doxou">Yamaha Y16ZR Doxou</option>');
                $('#vehicle-model').append('<option value="Yamaha Tenere 700">Yamaha Tenere 700</option>');
                break;
            case 'Honda':
                $('#vehicle-model').append('<option value="Honda RS-X">Honda RS-X</option>');
                $('#vehicle-model').append('<option value="Honda CBR250RR">Honda CBR250RR</option>');
                $('#vehicle-model').append('<option value="Honda CBR150R">Honda CBR150R</option>');
                $('#vehicle-model').append('<option value="Honda BeAT">Honda BeAT</option>');
                $('#vehicle-model').append('<option value="Honda ADV160">Honda ADV160</option>');
                $('#vehicle-model').append('<option value="Honda RS150R">Honda RS150R</option>');
                $('#vehicle-model').append('<option value="Honda X-ADV">Honda X-ADV</option>');
                $('#vehicle-model').append('<option value="Honda EX5">Honda EX5</option>');
                $('#vehicle-model').append('<option value="Honda CB250R">Honda CB250R</option>');
                $('#vehicle-model').append('<option value="Honda Vario">Honda Vario</option>');
                $('#vehicle-model').append('<option value="Honda CBR650R">Honda CBR650R</option>');
                $('#vehicle-model').append('<option value="Honda Dash 125">Honda Dash 125</option>');
                $('#vehicle-model').append('<option value="Honda Rebel 500">Honda Rebel 500</option>');
                $('#vehicle-model').append('<option value="Honda CB500X">Honda CB500X</option>');
                $('#vehicle-model').append('<option value="Honda Wave125i">Honda Wave125i</option>');
                $('#vehicle-model').append('<option value="Honda CBR600RR">Honda CBR600RR</option>');
                $('#vehicle-model').append('<option value="Honda CB500F">Honda CB500F</option>');
                $('#vehicle-model').append('<option value="Honda Forza">Honda Forza</option>');
                $('#vehicle-model').append('<option value="Honda Wave Alpha">Honda Wave Alpha</option>');
                $('#vehicle-model').append('<option value="Honda ADV 150">Honda ADV 150</option>');
                $('#vehicle-model').append('<option value="Honda CB650R">Honda CB650R</option>');
                $('#vehicle-model').append('<option value="Honda MSX125 SF">Honda MSX125 SF</option>');
                $('#vehicle-model').append('<option value="Honda CRF250">Honda CRF250</option>');
                $('#vehicle-model').append('<option value="Honda PCX">Honda PCX</option>');
                $('#vehicle-model').append('<option value="Honda CBR500R">Honda CBR500R</option>');
                $('#vehicle-model').append('<option value="Honda CBR1000RR-R">Honda CBR1000RR-R</option>');
                $('#vehicle-model').append('<option value="Honda GL1800 Gold Wing">Honda GL1800 Gold Wing</option>');
                $('#vehicle-model').append('<option value="Honda CRF1100L Africa Twin">Honda CRF1100L Africa Twin</option>');
                $('#vehicle-model').append('<option value="Honda CBR1000RR">Honda CBR1000RR</option>');
                $('#vehicle-model').append('<option value="Honda CB1000R">Honda CB1000R</option>');
                $('#vehicle-model').append('<option value="Honda CRF1100L Africa Twin Adventure Sports">Honda CRF1100L Africa Twin Adventure Sports</option>');
                break;
            case 'Kawasaki':
                $('#vehicle-model').append('<option value="Kawasaki Ninja 250">Kawasaki Ninja 250</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z125 PRO">Kawasaki Z125 PRO</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 250 SL">Kawasaki Ninja 250 SL</option>');
                $('#vehicle-model').append('<option value="Kawasaki Vulcan S">Kawasaki Vulcan S</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z 250">Kawasaki Z 250</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z900 ABS">Kawasaki Z900 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 650 ABS">Kawasaki Ninja 650 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 400">Kawasaki Ninja 400</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z900">Kawasaki Z900</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-6R">Kawasaki Ninja ZX-6R</option>');
                $('#vehicle-model').append('<option value="Kawasaki Vulcan 900 Classic">Kawasaki Vulcan 900 Classic</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys 650">Kawasaki Versys 650</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-25RR">Kawasaki Ninja ZX-25RR</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja H2">Kawasaki Ninja H2</option>');
                $('#vehicle-model').append('<option value="Kawasaki KLX150BF">Kawasaki KLX150BF</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys 1000 SE">Kawasaki Versys 1000 SE</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja H2SX">Kawasaki Ninja H2SX</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys-X 250">Kawasaki Versys-X 250</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z650 ABS">Kawasaki Z650 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z900 SE">Kawasaki Z900 SE</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 250 ABS">Kawasaki Ninja 250 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki 1400 GTR ABS">Kawasaki 1400 GTR ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki KLX450R">Kawasaki KLX450R</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-14R ABS">Kawasaki Ninja ZX-14R ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX450F">Kawasaki KX450F</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z 1000">Kawasaki Z 1000</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX65">Kawasaki KX65</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z900RS">Kawasaki Z900RS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys 1000GT">Kawasaki Versys 1000GT</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-10 RR">Kawasaki Ninja ZX-10 RR</option>');
                $('#vehicle-model').append('<option value="Kawasaki J300 ABS">Kawasaki J300 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX250F">Kawasaki KX250F</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX85-D">Kawasaki KX85-D</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja ZX-10R">Kawasaki Ninja ZX-10R</option>');
                $('#vehicle-model').append('<option value="Kawasaki Vulcan S ABS">Kawasaki Vulcan S ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki W800">Kawasaki W800</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 1000 ABS">Kawasaki Ninja 1000 ABS</option>');
                $('#vehicle-model').append('<option value="Kawasaki Ninja 1000SX">Kawasaki Ninja 1000SX</option>');
                $('#vehicle-model').append('<option value="Kawasaki Versys 1000 STD">Kawasaki Versys 1000 STD</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z 400">Kawasaki Z 400</option>');
                $('#vehicle-model').append('<option value="Kawasaki Z H2 SE">Kawasaki Z H2 SE</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX 250X">Kawasaki KX 250X</option>');
                $('#vehicle-model').append('<option value="Kawasaki KX 250">Kawasaki KX 250</option>');
                $('#vehicle-model').append('<option value="Kawasaki KLX 140R">Kawasaki KLX 140R</option>');
                break;
            case 'Sym':
                $('#vehicle-model').append('<option value="Sym Jet14 200">Sym Jet14 200</option>');
                $('#vehicle-model').append('<option value="Sym Husky 150">Sym Husky 150</option>');
                $('#vehicle-model').append('<option value="Sym Mio 110">Sym Mio 110</option>');
                $('#vehicle-model').append('<option value="Sym Sport Rider 125i">Sym Sport Rider 125i</option>');
                $('#vehicle-model').append('<option value="Sym Tuscany">Sym Tuscany</option>');
                $('#vehicle-model').append('<option value="Sym VF3i 185 Pro">Sym VF3i 185 Pro</option>');
                $('#vehicle-model').append('<option value="Sym Maxsym">Sym Maxsym</option>');
                $('#vehicle-model').append('<option value="Sym Jet X">Sym Jet X</option>');
                break;
            case 'Harley-Davidson':
                $('#vehicle-model').append('<option value="Harley-Davidson Street Bob">Street Bob</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Low Rider">Low Rider</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Fat Boy">Fat Boy</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Sportster S">Sportster S</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Nightster">Nightster</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Road Glide">Road Glide</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Nightster Special">Nightster Special</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Road King">Road King</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Low Rider ST">Low Rider ST</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Pan America 1250">Pan America 1250</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Ultra Limited">Ultra Limited</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Fat Bob">Fat Bob</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Tri Glide Ultra">Tri Glide Ultra</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Heritage Classic">Heritage Classic</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Sport Glide">Sport Glide</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Breakout 117">Breakout 117</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Road Glide ST">Road Glide ST</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson CVO Road Glide">CVO Road Glide</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Street Glide">Street Glide</option>');
                $('#vehicle-model').append('<option value="Harley-Davidson Freewheeler">Freewheeler</option>');
                break;
            case 'Suzuki':
                $('#vehicle-model').append('<option value="Suzuki Raider 150 Fi">Raider 150 Fi</option>');
                $('#vehicle-model').append('<option value="Suzuki V-Strom 650">V-Strom 650</option>');
                $('#vehicle-model').append('<option value="Suzuki GSX-R150">GSX-R150</option>');
                $('#vehicle-model').append('<option value="Suzuki V-Strom 800DE">V-Strom 800DE</option>');
                $('#vehicle-model').append('<option value="Suzuki GSX-R 1000">GSX-R 1000</option>');
                $('#vehicle-model').append('<option value="Suzuki GSX-S750">GSX-S750</option>');
                $('#vehicle-model').append('<option value="Suzuki GSX-S1000">GSX-S1000</option>');
                $('#vehicle-model').append('<option value="Suzuki Burgman 400">Burgman 400</option>');
                $('#vehicle-model').append('<option value="Suzuki Hayabusa">Hayabusa</option>');
                $('#vehicle-model').append('<option value="Suzuki Gixxer 250">Gixxer 250</option>');
                break;
            case 'Benelli':
                $('#vehicle-model').append('<option value="Benelli VZ 125i">VZ 125i</option>');
                $('#vehicle-model').append('<option value="Benelli TNT 25">TNT 25</option>');
                $('#vehicle-model').append('<option value="Benelli RFS 150I">RFS 150I</option>');
                $('#vehicle-model').append('<option value="Benelli TRK 502">TRK 502</option>');
                $('#vehicle-model').append('<option value="Benelli TNT 135">TNT 135</option>');
                break;
            case 'Ducati':
                $('#vehicle-model').append('<option value="Ducati Streetfighter V2">Streetfighter V2</option>');
                $('#vehicle-model').append('<option value="Ducati Panigale V4">Panigale V4</option>');
                $('#vehicle-model').append('<option value="Ducati Monster 821">Monster 821</option>');
                $('#vehicle-model').append('<option value="Ducati Scrambler Icon">Scrambler Icon</option>');
                $('#vehicle-model').append('<option value="Ducati Hypermotard 950">Hypermotard 950</option>');
                $('#vehicle-model').append('<option value="Ducati Panigale V2">Panigale V2</option>');
                $('#vehicle-model').append('<option value="Ducati Scrambler Nightshift">Scrambler Nightshift</option>');
                $('#vehicle-model').append('<option value="Ducati Multistrada V4">Multistrada V4</option>');
                $('#vehicle-model').append('<option value="Ducati Desert X">Desert X</option>');
                $('#vehicle-model').append('<option value="Ducati Monster SP">Monster SP</option>');
                $('#vehicle-model').append('<option value="Ducati Multistrada V2">Multistrada V2</option>');
                $('#vehicle-model').append('<option value="Ducati Panigale V4 SP2">Panigale V4 SP2</option>');
                $('#vehicle-model').append('<option value="Ducati Panigale V4R">Panigale V4R</option>');
                break;
            case 'BMW':
                $('#vehicle-model').append('<option value="BMW CE 04">CE 04</option>');
                $('#vehicle-model').append('<option value="BMW G 310 GS">G 310 GS</option>');
                $('#vehicle-model').append('<option value="BMW S 1000 XR">S 1000 XR</option>');
                $('#vehicle-model').append('<option value="BMW C 400 GT">C 400 GT</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 GS">R 1250 GS</option>');
                $('#vehicle-model').append('<option value="BMW K 1600 GTL">K 1600 GTL</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 GS Adventure">R 1250 GS Adventure</option>');
                $('#vehicle-model').append('<option value="BMW G 310 R">G 310 R</option>');
                $('#vehicle-model').append('<option value="BMW S 1000 R">S 1000 R</option>');
                $('#vehicle-model').append('<option value="BMW C 400 X">C 400 X</option>');
                $('#vehicle-model').append('<option value="BMW K 1600 GT">K 1600 GT</option>');
                $('#vehicle-model').append('<option value="BMW S 1000 RR">S 1000 RR</option>');
                $('#vehicle-model').append('<option value="BMW K 1600 B">K 1600 B</option>');
                $('#vehicle-model').append('<option value="BMW R Nine T">R Nine T</option>');
                $('#vehicle-model').append('<option value="BMW F 900 XR">F 900 XR</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 RT">R 1250 RT</option>');
                $('#vehicle-model').append('<option value="BMW R Nine T Scrambler">R Nine T Scrambler</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 RS">R 1250 RS</option>');
                $('#vehicle-model').append('<option value="BMW F 900 R">F 900 R</option>');
                $('#vehicle-model').append('<option value="BMW R Nine T Urban G/S">R Nine T Urban G/S</option>');
                $('#vehicle-model').append('<option value="BMW R Nine T Pure">R Nine T Pure</option>');
                $('#vehicle-model').append('<option value="BMW R18 First Edition">R18 First Edition</option>');
                $('#vehicle-model').append('<option value="BMW R 1250 R">R 1250 R</option>');
                $('#vehicle-model').append('<option value="BMW M 1000 R">M 1000 R</option>');
                $('#vehicle-model').append('<option value="BMW R18 Transcontinental">R18 Transcontinental</option>');
                $('#vehicle-model').append('<option value="BMW R18 Classic">R18 Classic</option>');
                $('#vehicle-model').append('<option value="BMW M 1000 RR">M 1000 RR</option>');
                $('#vehicle-model').append('<option value="BMW R18 Bagger">R18 Bagger</option>');
                break;
            case 'Vespa':
                $('#vehicle-model').append('<option value="Vespa Sprint 150">Sprint 150</option>');
                $('#vehicle-model').append('<option value="Vespa S 125">S 125</option>');
                $('#vehicle-model').append('<option value="Vespa Primavera 150">Primavera 150</option>');
                $('#vehicle-model').append('<option value="Vespa GTS Super">GTS Super</option>');
                break;
            case 'Aprilia':
                $('#vehicle-model').append('<option value="Aprilia SR GT 200">SR GT 200</option>');
                $('#vehicle-model').append('<option value="Aprilia RS 660">RS 660</option>');
                $('#vehicle-model').append('<option value="Aprilia RSV4 1100 Factory">RSV4 1100 Factory</option>');
                $('#vehicle-model').append('<option value="Aprilia Tuono V4">Tuono V4</option>');
                $('#vehicle-model').append('<option value="Aprilia Tuono 660">Tuono 660</option>');
                $('#vehicle-model').append('<option value="Aprilia Tuareg 660">Tuareg 660</option>');
                $('#vehicle-model').append('<option value="Aprilia RS 660 Extrema">RS 660 Extrema</option>');
                break;
            case 'Daiichi':
                $('#vehicle-model').append('<option value="Daiichi Sirius 110 Z">Sirius 110 Z</option>');
                $('#vehicle-model').append('<option value="Daiichi Megelli 250 SR">Megelli 250 SR</option>');
                $('#vehicle-model').append('<option value="Daiichi Megelli 250 MR">Megelli 250 MR</option>');
                $('#vehicle-model').append('<option value="Daiichi Megelli 250 RR">Megelli 250 RR</option>');
                $('#vehicle-model').append('<option value="Daiichi Cfmoto 650 TR">Cfmoto 650 TR</option>');
                $('#vehicle-model').append('<option value="Daiichi Caro Pro 110">Caro Pro 110</option>');
                $('#vehicle-model').append('<option value="Daiichi Cfmoto 650 NK">Cfmoto 650 NK</option>');
                $('#vehicle-model').append('<option value="Daiichi Caro 70 AX">Caro 70 AX</option>');
                break;
            case 'Modenas':
                $('#vehicle-model').append('<option value="Modenas Elegan 250">Elegan 250</option>');
                $('#vehicle-model').append('<option value="Modenas Kriss 110">Kriss 110</option>');
                $('#vehicle-model').append('<option value="Modenas Pulsar RS200">Pulsar RS200</option>');
                $('#vehicle-model').append('<option value="Modenas Karisma 125S">Karisma 125S</option>');
                $('#vehicle-model').append('<option value="Modenas CT 115S">CT 115S</option>');
                $('#vehicle-model').append('<option value="Modenas Kriss MR2">Kriss MR2</option>');
                $('#vehicle-model').append('<option value="Modenas Dominar D400">Dominar D400</option>');
                $('#vehicle-model').append('<option value="Modenas Pulsar NS200">Pulsar NS200</option>');
                $('#vehicle-model').append('<option value="Modenas V15">V15</option>');
                $('#vehicle-model').append('<option value="Modenas Pulsar NS160">Pulsar NS160</option>');
                break;
            case 'Piaggio':
                $('#vehicle-model').append('<option value="Piaggio Medley S 150">Medley S 150</option>');
                break;
            case 'Moto Guzzi':
                $('#vehicle-model').append('<option value="Moto Guzzi V85 TT">V85 TT</option>');
                $('#vehicle-model').append('<option value="Moto Guzzi V100">V100</option>');
                $('#vehicle-model').append('<option value="Moto Guzzi V7">V7</option>');
                break;
            case 'GPX':
                $('#vehicle-model').append('<option value="GPX Demon GR200R">Demon GR200R</option>');
                $('#vehicle-model').append('<option value="GPX Legend 150S">Legend 150S</option>');
                $('#vehicle-model').append('<option value="GPX Legend 250 Twin">Legend 250 Twin</option>');
                $('#vehicle-model').append('<option value="GPX POPZ 110">POPZ 110</option>');
                $('#vehicle-model').append('<option value="GPX Demon 150GN">Demon 150GN</option>');
                break;
            case 'Royal Enfield':
                $('#vehicle-model').append('<option value="Royal Enfield Classic 350">Classic 350</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Meteor 350">Meteor 350</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Hunter 350">Hunter 350</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Interceptor 650">Interceptor 650</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Continental GT 650">Continental GT 650</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Himalayan">Himalayan</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Super Meteor 650">Super Meteor 650</option>');
                $('#vehicle-model').append('<option value="Royal Enfield Scram 411">Scram 411</option>');
                break;
            case 'Brixton':
                $('#vehicle-model').append('<option value="Brixton BX 150 R">BX 150 R</option>');
                $('#vehicle-model').append('<option value="Brixton BX 150 X">BX 150 X</option>');
                $('#vehicle-model').append('<option value="Brixton BX 150">BX 150</option>');
                $('#vehicle-model').append('<option value="Brixton Cromwell 1200">Cromwell 1200</option>');
                break;

                //van
            case 'Daihatsu':
                $('#vehicle-model').append('<option value="Daihatsu Gran Max (Van)">Gran Max</option>');
                break;
            case 'Foton':
                $('#vehicle-model').append('<option value="Foton View CS2">View CS2</option>');
                $('#vehicle-model').append('<option value="Foton View C2">View C2</option>');
                $('#vehicle-model').append('<option value="Foton Daimler EST A">EST A (Lorry)</option>');
                $('#vehicle-model').append('<option value="Foton Daimler EST">EST (Lorry)</option>');
                $('#vehicle-model').append('<option value="Foton Toplander">Toplander (Lorry)</option>');
                break;

                //lorry
            case 'Fuso':
                $('#vehicle-model').append('<option value="Fuso FN62FM">FN62FM</option>');
                $('#vehicle-model').append('<option value="Fuso FM65FN">FM65FN</option>');
                $('#vehicle-model').append('<option value="Fuso FJ1828R">FJ1828R</option>');
                $('#vehicle-model').append('<option value="Fuso FM65FJ">FM65FJ</option>');
                $('#vehicle-model').append('<option value="Fuso FG83PE">FG83PE</option>');
                $('#vehicle-model').append('<option value="Fuso FE71PB">FE71PB</option>');
                $('#vehicle-model').append('<option value="Fuso FE85PG">FE85PG</option>');
                $('#vehicle-model').append('<option value="Fuso FE85PE">FE85PE</option>');
                break;
            case 'Hino':
                $('#vehicle-model').append('<option value="Hino 300 Series">300 Series</option>');
                $('#vehicle-model').append('<option value="Hino 500 Series">500 Series</option>');
                $('#vehicle-model').append('<option value="Hino 700 Series">700 Series</option>');
                break;
            case 'UD Trucks':
                $('#vehicle-model').append('<option value="UD Trucks Quester GKE">Quester GKE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester CWE">Quester CWE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Croner LKE">Croner LKE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester CDE">Quester CDE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester GWE">Quester GWE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester CKE">Quester CKE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester GDE">Quester GDE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Kuzer RKE">Kuzer RKE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Quester CGE">Quester CGE</option>');
                $('#vehicle-model').append('<option value="UD Trucks Croner PKE">Croner PKE</option>');
                break;
            case 'CAMC':
                $('#vehicle-model').append('<option value="CAMC Tractor Unit">Tractor Unit</option>');
                $('#vehicle-model').append('<option value="CAMC Tipper-Dump">Tipper-Dump</option>');
                $('#vehicle-model').append('<option value="CAMC Cargo">Cargo</option>');
                $('#vehicle-model').append('<option value="CAMC Mixer Truck">Mixer Truck</option>');
                $('#vehicle-model').append('<option value="CAMC Special">Special</option>');
                break;
            case 'JMC':
                $('#vehicle-model').append('<option value="JMC Potente">Potente</option>');
                $('#vehicle-model').append('<option value="JMC N800">N800</option>');
                break;

        }
    });
});